# <b><font color='teal'>Практикум</font></b>

### <font color='teal'>Задание 1</font>
Напишите программу, которая:
- Запрашивает у пользователя ввод двух списков – в первом 5 элементов, во втором 4. Списки вводятся в виде чисел, разделенных пробелами.
- Объединяет введенные списки в один новый список из 9 элементов.
- Преобразует полученный список в массив NumPy.
- Вычисляет минимальное, среднее и максимальное значение для полученного массива.

*** Дополнительно реализовать контроль выполнения условия (определить поведение программы при неправильной длине введенных списков)

In [13]:
import numpy as np

#1. Запрашиваем ввод данных от пользователя с помощью команды input()
str_1 = input("Введите 5 чисел для первого списка через пробел: ")
print(str_1)
str_2 = input("Введите 4 числа для второго списка через пробел: ") 
print(str_2)
main_list = str_1 + " " + str_2

#2. Используем команду split(), чтобы разделить числа. По умолчанию в данной команде используется разделитель - пробел
list_ = main_list.split()
# print(list_)
#3. С помощью map() преобразуем все элементы списка в числа. Помним, что все, что вводит пользователь, python считывает как строка
list_ = list(map(int, list_))
# print(list_)
#4. "Обертываем" строку в список

#Все эти действия можно объединить в одну строку


#Объединяем два списка в 1

#Преобразуем список в массив NumPy
arr = np.array(list_)
# print(arr)
#Вычисляем минимальное, среднее, максимальное для полученного массива
print("Минимальное значение:", np.min(arr))
print("Среднее значение:", np.mean(arr))
print("Максимальное значение:", np.max(arr))


9 8 7 6 5
1 2 3 4
Минимальное значение: 1
Среднее значение: 5.0
Максимальное значение: 9


## <font color='teal'>Задание 2</font>
С помощью функции np.linspace создайте массив из 9 элементов со значениями между средним и максимальным из предыдущей задачи. Найдите поэлементную сумму массивов из первой и второй задачи.

In [34]:
#Создадим массив согласно условию 
#(первый аргумент - начало массива, второй аргумент - конец массива, третий - кол-во элментов в массиве)
print(arr)
arr_2 = np.linspace(np.mean(arr), np.max(arr), 9)
print(arr_2)
print("-"*80)

print(arr + arr_2)

[9 8 7 6 5 1 2 3 4]
[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9. ]
--------------------------------------------------------------------------------
[14.  13.5 13.  12.5 12.   8.5 10.  11.5 13. ]


### <font color='teal'>Задание 3</font>
Создайте массив из десяти элементов 1, 2, …, 10. С помощью функции cumprod вычислите кумулятивные произведения элементов этого массива.

In [ ]:
#Создадим массив согласно условию с помощью функции arange
arr_3 = np.arange(1, 11, 1)
print(arr_3)
print("-"*80)
#Кумулятивное произведение вычисляется подобно кумулятивной сумме, которое мы рассматривали на занятии
print(np.cumprod(arr_3))

[ 1  2  3  4  5  6  7  8  9 10]
--------------------------------------------------------------------------------
[      1       2       6      24     120     720    5040   40320  362880
 3628800]


### <font color='teal'>Задание 4</font>
Напишите программу, которая:
- Запрашивает у пользователя ввод трех списков, каждый из трех элементов. Списки вводятся в виде чисел, разделенных пробелами.
- Создает список из полученных списков.
- Преобразует полученный двумерный список в двумерный массив NumPy (назовем его матрицей А).
- Вычисляет среднее значение для полученного массива.

In [38]:
#Создадим пустой список, в который будем аггрегировать списки из 3 элементов
list_1 = list(map(int, input("Введите 3 чисел для первого списка через пробел: ").split()))
print(list_1)
list_2 = list(map(int, input("Введите 3 числа для второго списка через пробел: ").split()))
print(list_2)
list_3 = list(map(int, input("Введите 3 числа для третьего списка через пробел: ").split()))
print(list_3)
arr_A = np.array([list_1, list_2, list_3])
print(arr_A)
print("Среднее значение:", np.mean(arr_A))

#Организуем цикл по созданию списков из 3-х элементов
#На каждой итерации запрашиваем 3 элемента, записываем их в спискок и получившийся список добавляем в список списков

#Получившийся список списков преобразуем в матрицу

#С помощью функции mean() считаем среднее значение


[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Среднее значение: 5.0


### <font color='teal'>Задание 5</font>
Продолжите предыдущую программу. Далее она:
- Создает матрицу такого же размера, но заполненную вычисленным средним значением (назовем ее матрицей B).
- Разделите матрицу A на матрицу B - это будет матрица С.
- Создайте новую матрицу, заполненную логическими значениями – True, если элемент матрицы С больше 1, False – если меньше 1.

In [43]:
#Создаем матрицу B с помощью функции full (первый аргумент - размерность массива, второй аргумент - чем заполнить элементы массива)
arr_B = np.full_like(arr_A, np.mean(arr_A), dtype=float)
print(arr_B)
print("-"*80)
#Делим матрицу A на B
arr_C = arr_A / arr_B
print(arr_C)
print("-"*80)
#Создаем логическую матрицу по условию элемент > 1
arr_D = arr_C > 1
print(arr_D)


[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
--------------------------------------------------------------------------------
[[0.2 0.4 0.6]
 [0.8 1.  1.2]
 [1.4 1.6 1.8]]
--------------------------------------------------------------------------------
[[False False False]
 [False False  True]
 [ True  True  True]]


### <font color='teal'>Задание 6</font>
Продолжите предыдущую программу. Далее она:
- Объединяет матрицы A и B в две новые матрицы – одну размера 3х6, другую – 6х3.
- Запрашивает у пользователя два числа - x и y.
- Первую матрицу умножает на x, из второй вычитает y.

In [27]:
# Формируем матрицу 3x6 вручную (объединение по горизонтали)
arr_AB_36 = np.concatenate((arr_A, arr_B), axis=1)
print(arr_AB_36)
# Формируем матрицу 6x3 (объединение по вертикали)
arr_AB_63 = np.concatenate((arr_A, arr_B), axis=0)
print(arr_AB_63)


[[1. 2. 3. 4. 5. 6.]
 [4. 5. 6. 4. 5. 6.]
 [7. 8. 9. 4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]


### <font color='teal'>Задание 7</font>
Напишите программу, которая запрашивает у пользователя три числа и создает трехмерный массив соответствующей размерности, заполненный случайными числами. Выведите массив на экран.

In [32]:
num_1 = list(map(int, input("Введите число для проверки делимости на 3: ").split()))
arr_new_3 = np.empty(num_1, int)
print(arr_new_3)

[[[23925768157397016 32370111954616435     2441550839344]
  [    2441550838928     2441456028096     2441550838320]
  [    2441550838352     2441550838640     2441550837552]]

 [[    2441551187968     2441550838448     2441542101216]
  [    2441550837904     2441511557376     2441542100928]
  [    2441550837744     2441550837776     2441542099200]]

 [[    2441554261856     2441550838480                 0]
  [                0                 0                 0]
  [                0                 0      519698382894]]]
