# <b><font color='teal'>Введение в Numpy, массивы</font></b>

### <font color='teal'>1. Что такое NumPy и зачем он нужен</font>

In [1]:
# Установка библиотеки NumPy
!pip install numpy

In [2]:
#Подключение библиотеки NumPy
import numpy as np

In [3]:
#Получение справочной информации по функциям
help(np.mean)

Help on _ArrayFunctionDispatcher in module numpy:

mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>
)
    Compute the arithmetic mean along the specified axis.

    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.

        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For in

##### <font color='teal'>Официальная документация по библиотеке NumPy</font>
- <a href="https://numpy.org/devdocs/user/" target="_blank">User Guide</a>
- <a href="https://numpy.org/doc/1.23/numpy-user.pdf" target="_blank">User Guide (PDF)</a>

### <font color='teal'>2. Создание массивов</font>
- <i>вектор - одномерный массив</i>
- <i>матрица - двумерный массив</i>
- <i>вектор-столбец - двумерный массив с одним столбцом </i>

In [4]:
#Способ №1 - из списка
#Вектор
one_d_array = np.array([1, 2, 3])
print('Вектор: ',one_d_array)
#Матрица
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print('Матрица: \n',two_d_array)
#Вектор-столбец
col = np.array([[10], [20], [30]])
print('Вектор-столбец: \n',col)

Вектор:  [1 2 3]
Матрица: 
 [[1 2 3]
 [4 5 6]]
Вектор-столбец: 
 [[10]
 [20]
 [30]]


In [5]:
#Способ №2 - с помощью функции arange(начало диапазона, конец диапазона, шаг)
a = np.arange(0, 9, 2)
print(a)

[0 2 4 6 8]


In [7]:
print("Целочисленный массив: ", np.arange(0, 9, 2))
print("Массив десятичных чисел: ", np.arange(0.0, 8.0, 0.5))

Целочисленный массив:  [0 2 4 6 8]
Массив десятичных чисел:  [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]


In [8]:
#Способ №3 - с помощью функции linspace(начало диапазона, конец диапазона, количество чисел в массиве)
a = np.linspace(0, 8, 7)
print(a)

[0.         1.33333333 2.66666667 4.         5.33333333 6.66666667
 8.        ]


#### <font color='teal'>2.1. Специальные функции для создания массивов</font>
- <i>empty_like(), empty()</i>
- <i>ones_like(), ones()</i>
- <i>zeros_like(), zeros()</i>
- <i>full_like, full()</i>

In [9]:
#empty_like()
#Возвращает новый массив той же формы и типа, что и заданный массив
a = ([1,2,3], [4,5,6])
np.empty_like(a)

array([[4608683618675807573, 4613187218303178069, 4616189618054758400],
       [4617690817930548565, 4619192017806338730, 4620693217682128896]])

In [4]:
#empty()
#Возвращает новый массив заданной формы и типа
np.empty([2, 2], float)

array([[2.16851034e+243, 4.27242994e+180],
       [1.69505626e+190, 2.19480969e-312]])

In [11]:
#ones_like()
#Возвращает массив единиц той же формы и типа, что и заданный массив
a = ([1,2,3], [4,5,6])
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
#ones()
#Возвращает новый массив заданной формы и типа, заполненный единицами
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
#zeros_like()
#Возвращает массив нулей той же формы и типа, что и заданный массив
a = ([1,2,3], [4,5,6])
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
#zeros()
#Возвращает новый массив заданной формы и типа, заполненный нулями
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
#full_like()
#Возвращает заполненный массив той же формы и типа, что и заданный массив
a = ([1,2,3], [4,5,6])
np.full_like(a, 255)

array([[255, 255, 255],
       [255, 255, 255]])

In [16]:
#full()
#Возвращает новый массив заданной формы и типа, заполненный указанными значениями
np.full((3,3), 255)

array([[255, 255, 255],
       [255, 255, 255],
       [255, 255, 255]])

### <font color='teal'>3. Работа с размерностями</font>

In [19]:
#Просмотр размерности
three_d_array = np.array([
                            [
                                [1, 2], [3, 4]
                            ], 
                            [
                                [5, 6], [7, 8]
                            ], 
                            [
                                [9, 10], [11, 12]
                            ]
                        ])
three_d_array.ndim 

3

In [20]:
#Просмотр длины массивов по каждой размерности
three_d_array.shape

(3, 2, 2)

In [21]:
#Просмотр длины внешнего массива
len(three_d_array)

3

In [22]:
#Просмотр общего количества элементов
three_d_array.size

12

#### <font color='teal'>3.1. Задания для закрепления</font>

##### 1) Сколько строк и столбцов будет у матрицы, которая будет выведена следующим кодом?

In [25]:
array = np.array([
                [1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9], 
                [10, 11, 12]
                ])
print(array)
print(array.ndim) 
print(len(array)) 
print(array.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
4
(4, 3)


##### 2) Что выведет следующий код?

In [27]:
print(array.shape)
print(len(array))
print(array.size)

(4, 3)
4
12


### <font color='teal'>4. Типы элементов в массивах</font>

In [28]:
#Массив целых чисел
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
two_d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
two_d_array = np.array([[1, 2, 3.5], [4, 5, 6]])
two_d_array

array([[1. , 2. , 3.5],
       [4. , 5. , 6. ]])

In [30]:
two_d_array = np.array([[1, 2, 3], ["A", "B", "C"]])
two_d_array

array([['1', '2', '3'],
       ['A', 'B', 'C']], dtype='<U21')

In [31]:
two_d_array = np.array([[1, 2, 3], ["A", "B", "C" * 38]])
two_d_array

array([['1', '2', '3'],
       ['A', 'B', 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC']], dtype='<U38')

In [32]:
#Измерение объема памяти для хранения массива
a = np.array([1.0, 2, '3'])

In [33]:
a.dtype

dtype('<U32')

In [34]:
a.itemsize

128

In [35]:
b = np.array([1, 2, 3])
b.itemsize

8

In [36]:
#Попробуем добавить новый элемент в массив
two_d_array = np.array([[1, 2, 3], ["A", "B", "C"]])
two_d_array

array([['1', '2', '3'],
       ['A', 'B', 'C']], dtype='<U21')

In [37]:
two_d_array[0][0] = "a" * 100
two_d_array

array([['aaaaaaaaaaaaaaaaaaaaa', '2', '3'],
       ['A', 'B', 'C']], dtype='<U21')

In [38]:
#Получение списка из массива
two_d_array.tolist()

[['aaaaaaaaaaaaaaaaaaaaa', '2', '3'], ['A', 'B', 'C']]

In [39]:
#Задание типа данных вручную
float_array = np.array([1, 2, 3], dtype=np.float64)
float_array

array([1., 2., 3.])

In [40]:
string_array = np.array(["A", "B", "C"], dtype='U10')
string_array

array(['A', 'B', 'C'], dtype='<U10')

In [41]:
#Смена типа данных в массиве
int_array = np.array([1, 2, 3], dtype=np.int8)
print(int_array.astype(np.float32))

[1. 2. 3.]


### <font color='teal'>5. Решение задач</font>

##### 1) Что будет выведено в следующих случаях и почему?

In [42]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[1] + arr[3])

arr = np.array([1.0, 2, 3])
print(arr.dtype)

arr = np.arange(5, 15, 2)
print(arr)

6
float64
[ 5  7  9 11 13]


##### 2) Создайте одномерный массив из случайных чисел. Выведите его тип, размерность и содержимое.

In [50]:
array = np.empty((2, 3), int)
print(array)
print(np.ndim(array))
print(len(array))
print(array.dtype)

[[4607182418800017408 4611686018427387904 4615063718147915776]
 [4616189618054758400 4617315517961601024 4618441417868443648]]
2
2
int64


##### 3) Создайте массив размером 3x4, полностью заполненный единицами, и выведите его.

In [53]:
array_one = np.ones([3, 4])
print(array_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


##### 4) Используя функцию np.arange, создайте массив чисел от 0 до 10 с шагом 2. Затем создайте массив с теми же числами, используя np.linspace, и сравните результаты.

In [57]:
array_two = np.arange(0, 12, 2)
print(array_two)
array_lin = np.linspace(0, 10, 6)
print(array_lin)

[ 0  2  4  6  8 10]
[ 0.  2.  4.  6.  8. 10.]
