# <b><font color='teal'>Элементы матричной алгебры. Обратные матрицы и определитель</font></b>

### <font color='teal'>1. Векторы и операции над ними в практических задачах</font>

In [3]:
import numpy as np
# Вектор ежедневных расходов (в евро)
daily_expenses = np.array([10, 20, 15, 10, 30, 50, 50])

# Температура воздуха по месяцам (в градусах Цельсия)
temperature = np.array([1, 2, 6, 11, 16, 19, 21, 21, 16, 11, 6, 2])

In [4]:
# Перевод ежедневных расходов в доллары
daily_expenses_usd = daily_expenses * 1.15  # Предположим, что 1 евро = 1.15 доллара
print("Ежедневные расходы в долларах:", daily_expenses_usd)
# Перевод температуры в Фаренгейты
temperature_fahrenheit = temperature * 9/5 + 32  # Предположим, что температура в Цельсиях
print("Температура в Фаренгейтах:", temperature_fahrenheit)

Ежедневные расходы в долларах: [11.5  23.   17.25 11.5  34.5  57.5  57.5 ]
Температура в Фаренгейтах: [33.8 35.6 42.8 51.8 60.8 66.2 69.8 69.8 60.8 51.8 42.8 35.6]


#### <font color='teal'>2.1. Поясните, что вычисляется в следующих примерах</font>

In [5]:
print(daily_expenses.sum())
print(temperature.mean())
print(daily_expenses.max())
print(temperature[5:8])

185
11.0
50
[19 21 21]


In [6]:
# Доходы мужа по месяцам (в евро)
income_m = np.array([2000, 3000, 3500, 3000, 3000, 2500, 3500, 2000, 2500, 3000, 3500, 4000])

# Доходы жены по месяцам (в евро)
income_f = np.array([1500, 2500, 6000, 1100, 1600, 1900, 2100, 4200, 6000, 1100, 6000, 2000])

# Курс евро к доллару по месяцам
eur2usd = np.array([1.0779, 1.0716, 1.071, 1.096, 1.0879, 1.0834, 1.1056, 1.0916, 1.0686, 1.0561, 1.0804, 1.0902])

# Семейный доход в евро
income_family_eur = income_m + income_f
print("Семейный доход в евро:", income_family_eur)
# Семейный доход в долларах
income_family_usd = income_family_eur * eur2usd
print("Семейный доход в долларах:", income_family_usd)

Семейный доход в евро: [3500 5500 9500 4100 4600 4400 5600 6200 8500 4100 9500 6000]
Семейный доход в долларах: [ 3772.65  5893.8  10174.5   4493.6   5004.34  4766.96  6191.36  6767.92
  9083.1   4330.01 10263.8   6541.2 ]


### <font color='teal'>2. Матрицы в практических задачах</font>

<b>Задача №1</b><br>
Кондитерская производит несколько видов десертов. Для каждого необходимы мука, яйца и сахар, но в разном количестве. Необходимое количество опишем матрицей, в которой каждая строка описывает одну партию какого-то десерта, при этом первый столбец показывает количество муки в килограммах, второй столбец – количество яиц в штуках, третий – количество сахара в килограммах.

In [7]:
# Расход продуктов  
goods = np.array([[0.5, 6, 0.1],
                  [1, 10, 0.5],
                  [0.3, 10, 0.6],
                  [0.5, 7, 0.3]])

print(goods)

[[ 0.5  6.   0.1]
 [ 1.  10.   0.5]
 [ 0.3 10.   0.6]
 [ 0.5  7.   0.3]]


In [8]:
goods.T

array([[ 0.5,  1. ,  0.3,  0.5],
       [ 6. , 10. , 10. ,  7. ],
       [ 0.1,  0.5,  0.6,  0.3]])

In [12]:
#Стоимость единицы продукта
prices = np.array([0.75, 0.22, 0.88])


In [14]:
#Посчитайте стоимость каждого вида десерта
prices @ goods.T 

array([1.783, 3.39 , 2.953, 2.179])

In [16]:
st = goods * prices
st.sum(axis=1)
print(st.sum(axis=1))

[1.783 3.39  2.953 2.179]


<b>Задача №2</b><br>
Фирма закупает ноутбуки и стационарные компьютеры для оборудования офисов на двух этажах здания. На первом этаже планируется поставить 20 стационарных компьютеров и 20 ноутбуков. На втором этаже – 12 стационарных компьютеров и 35 ноутбуков. Компьютер стоит 850 евро, ноутбук – 1125 евро. Запишите матрицу <i>equipment</i>, описывающую количество компьютеров и ноутбуков на каждом этаже. Запишите вектор-столбец <i>prices</i> с ценами компьютеров и ноутбуков. С помощью матричных операций вычислите стоимость оборудования на каждом этаже.

In [20]:
equipment = np.array([  [20, 20],
                        [12, 35]])
prices_equipment = np.array([850, 1125])
st_equipment = equipment * prices_equipment
print("Стоимость", st_equipment)
tot_equipment = equipment @ prices_equipment.T
print("Общая стоимость", tot_equipment)
tot2_equipment = st_equipment.sum(axis=1)
print("Общая стоимость (сумма по строкам)", tot2_equipment)

Стоимость [[17000 22500]
 [10200 39375]]
Общая стоимость [39500 49575]
Общая стоимость (сумма по строкам) [39500 49575]


### <font color='teal'>3. Системы уравнений и обратная матрица</font>

<b>Система уравнений</b> – это набор уравнений с несколькими переменными.<br>
<b>Решение системы уравнений</b> – это набор значений переменных, при подстановке которых в уравнения все они обращаются в верные равенства.

\begin{cases}
   20x + 20y = 40000 \\
   12x + 35y = 50000
\end{cases}

$$A = \begin{bmatrix}
   20 & 20 \\
   12 & 35
\end{bmatrix},
X = \begin{bmatrix}
   x \\
   y
\end{bmatrix},
B = \begin{bmatrix}
   40000 \\
   50000
\end{bmatrix}$$

$$AX = B$$

$$X = \dfrac{1}{A}* B = A^{-1}* B$$

Две матрицы называются <b>взаимнообратными</b>, если их произведение равно единичной матрице.

In [ ]:
equipment = np.array([[20, 20], [12, 35]])
expenses = np.array([[40000], [50000]])
#Получение обратной матрицы для equipment
inverse = np.linalg.inv(equipment)
print("Обратная матрица для equipment:\n", inverse)
print(inverse @ expenses)


Обратная матрица для equipment:
 [[ 0.07608696 -0.04347826]
 [-0.02608696  0.04347826]]
[[ 869.56521739]
 [1130.43478261]]
459.9999999999997


- <a href="https://mathprofi.ru/kak_naiti_obratnuyu_matricu.html" target="_blank">Как найти обратную матрицу</a>
- <a href="https://mathprofi.ru/metod_zhordano_gaussa_nahozhdenie_obratnoi_matricy.html" target="_blank">Метод Гаусса-Жордана</a>

Выполните проверку, что полученный вектор цен удовлетворяет матричному уравнению – подставьте значения в уравнения или выполните умножение матрицы на этот столбец.

In [24]:
x = inverse @ expenses
print(equipment @ x)

[[40000.]
 [50000.]]


### <font color='teal'>4. Определитель</font>
<i>Определитель</i> – специальная числовая характеристика матрицы. Система уравнений с данной матрицей имеет единственное решение, только если ее определитель не равен нулю.

In [25]:
equipment = np.array([[20, 20], [30, 30]])
inverse = np.linalg.inv(equipment)
print(inverse)

LinAlgError: Singular matrix

In [29]:
equipment = np.array([[20, 20], [30, 30]])
# inverse = np.linalg.inv(equipment)
# print(inverse)
det = np.linalg.det(equipment)

print(det)

0.0


In [31]:
# Вычислите определитель предыдущей версии матрицы
equipment = np.array([[20, 20], [12, 35]])
det = np.linalg.det(equipment)

print(det)

459.9999999999997


### <font color='teal'>6. Решение задач</font>

Матрица goods, как в примере выше, описывает количество муки, яиц и сахара в трех видах десертов некоторой кондитерской. Известно, что затраты на выпечку первого десерта составляют 2 евро, второго – 4 евро, третьего – 3 евро. Найдите, сколько должны стоить мука, яйца и сахар для такой себестоимости десертов.

In [4]:
# Расход продуктов  
goods = np.array([[0.5, 6, 0.1],
                  [1, 10, 0.5],
                  [0.3, 10, 0.6]])
price_keks = np.array([2, 4, 3])
det = np.linalg.det(goods)
print(det)
inverse_goods = np.linalg.inv(goods)
print("Обратная матрица для goods:\n", inverse_goods)
print("Результат умножения обратной матрицы на вектор цен:\n", inverse_goods @ price_keks.T)

-1.4999999999999998
Обратная матрица для goods:
 [[-0.66666667  1.73333333 -1.33333333]
 [ 0.3        -0.18        0.1       ]
 [-4.66666667  2.13333333  0.66666667]]
Результат умножения обратной матрицы на вектор цен:
 [1.6  0.18 1.2 ]


In [ ]:
# Для решения задачи составить систему уравнений, найти определитель этой системы. 
# Если определитель не равен нулю, найти обратную матрицу и значения переменных.