# <b><font color='teal'>Продолжение работы с матрицами. Многомерные массивы
</font></b>

### <font color='teal'>1. Единичная матрица, операции над матрицами</font>

<b> Единичная матрица </b>– это квадратная матрица, у которой на диагонали стоят единицы, а вне – нули. Свойство: при умножении на единичную матрицу исходная матрица не изменится.

In [2]:
import numpy as np
#Создание единичной матрицы
#Функция eye (обязательный параметр - кол-во строк и столбцов)
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
#Умножение матрицы на единичную
a = np.arange(16).reshape(4,4)
print(a)
print(a @ I)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


<p align="center">
  <img src="Images/indexes.png" alt="Индексы в матрице" width="400"/>
</p>

In [3]:
#Создание матрицы с помощью функции fromfunction()
# f - функция, с помощью которой будут заполняться элементы массива
# i - индексы строк
# j - индексы столбцов

def f(i, j):
    print(i)
    print(j)
    return 10 * i + j

print(np.fromfunction(f, (3, 4), dtype=np.int64))

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]


In [4]:
def f(i, j):
    return (i+1) * (j + 1)

print(np.fromfunction(f, (9, 9)))

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 9. 18. 27. 36. 45. 54. 63. 72. 81.]]


In [5]:
def f(i, j):
    return (i+j)**2

print(np.fromfunction(f, (5, 5)))

[[ 0.  1.  4.  9. 16.]
 [ 1.  4.  9. 16. 25.]
 [ 4.  9. 16. 25. 36.]
 [ 9. 16. 25. 36. 49.]
 [16. 25. 36. 49. 64.]]


In [6]:
#Объединение массивов
a = np.array([1, 3, 2])
b = np.array([4, 5, 6])
horizontal = np.hstack((a, b))
vertical = np.vstack((a, b))
print(horizontal)
print(vertical)

[1 3 2 4 5 6]
[[1 3 2]
 [4 5 6]]


In [33]:
#Расщепление массивов
#Функция hsplit (первый аргумент - какую матрицу, второй - после какого элемента "разрезать", считая от 1)
matrix_a = np.arange(1,10).reshape(3,3)
print(matrix_a)
print("--------------")
print(np.hsplit(matrix_a, [2]))
a = np.hsplit(matrix_a, [2])
print(a[0])
print("--------------")
print(a[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------
[array([[1, 2],
       [4, 5],
       [7, 8]]), array([[3],
       [6],
       [9]])]
[[1 2]
 [4 5]
 [7 8]]
--------------
[[3]
 [6]
 [9]]


In [27]:
#Функция vsplit (первый аргумент - какую матрицу, второй - после какого элемента "разрезать", считая от 1)
print(matrix_a)
print("--------------")
np.vsplit(matrix_a, [1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------


[array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]])]

In [16]:
#Сумма всех элементов, элементов столбцов, элементов строк
b = np.array([[4, 5, 6], [7, 8, 9]])
print(b)
print('Сумма всех элементов массива', b.sum()) 
print('Сумма элементов по столбцам', b.sum(axis=0))
print('Сумма элементов по строкам',b.sum(axis=1))

[[4 5 6]
 [7 8 9]]
Сумма всех элементов массива 39
Сумма элементов по столбцам [11 13 15]
Сумма элементов по строкам [15 24]


<b> След матрицы </b>– сумма диагональных элементов.

In [34]:
b = np.array([[4, 5, 6], [7, 8, 9]])
print(np.trace(b))

12


### <font color='teal'>2. Тензоры (многомерные массивы)</font>

In [35]:
X = np.arange(24).reshape(2, 3, 4)
print(X)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [36]:
#Суммирование в тензорах
print(X.sum(axis=0)) #axis = 0 обозначает, что мы выключаем внешнее измерение и суммируем только по строкам и столбцам, как будто накладываем первый массив и на второй, как в поэлементом сложении

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [37]:
print(X.sum(axis=1)) #axis = 1 обозначает, что мы выключаем строки, то есть в каждом внешнем измерении суммируем по столбцам

[[12 15 18 21]
 [48 51 54 57]]


In [38]:
print(X.sum(axis=2)) #axis = 2 обозначает, что мы выключаем столбцы, то есть в каждом внешнем измерении суммируем по строкам

[[ 6 22 38]
 [54 70 86]]


In [39]:
print(X.sum(axis=(1, 2)))#axis = 1, 2 обозначает, что мы выключаем столбцы и строки, и считаем сумму элементов массивов во внешнем измерении

[ 66 210]


In [40]:
print(X.sum(axis=(0, 1)))#axis = 0, 1 обозначает, что мы выключаем строки и внешнее измерение, и считаем сумму элементов по столбцам

[60 66 72 78]


In [41]:
print(X.sum(axis=(0, 2)))

[ 60  92 124]


### <font color='teal'>3. Добавление размерностей</font>

In [49]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
print(a.shape)
print("--------------")
b = a[np.newaxis, :] # добавление оси axis0
print(b)
print("--------------")
print(b.shape)
print("--------------")
c = a[np.newaxis, :, np.newaxis] # добавление оси axis1
print(c)
print("--------------")
print(c.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
--------------
[[ 1  2  3  4  5  6  7  8  9 10]]
--------------
(1, 10)
--------------
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
--------------
(1, 10, 1)


### <font color='teal'>4. Решение задач</font>

1) Что будет выведено в следующих случаях и почему?

In [52]:
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([0, 1, 2])
print(a)
print("--------------")
print(b)
result = a / (b + 1)
print(result)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
--------------
[0 1 2]
[[ 0.          0.          0.        ]
 [10.          5.          3.33333333]
 [20.         10.          6.66666667]
 [30.         15.         10.        ]]


Создайте два массива: первый - двумерный массив (матрица) размером 6x4, заполненный числами от 10 до 33; второй - одномерный массив длины 4 с числами от 15 до 18. Выполните поэлементное деление матрицы на одномерный массив, используя правила Broadcasting, и вычислите след результирующей матрицы.

In [54]:
a = np.arange(10, 34).reshape(6, 4)
print(a)
print("--------------")
b = np.arange(15,19)
с = a / b
print(с)
print("--------------")
res_c = np.trace(с) 
print(res_c)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]
--------------
[[0.66666667 0.6875     0.70588235 0.72222222]
 [0.93333333 0.9375     0.94117647 0.94444444]
 [1.2        1.1875     1.17647059 1.16666667]
 [1.46666667 1.4375     1.41176471 1.38888889]
 [1.73333333 1.6875     1.64705882 1.61111111]
 [2.         1.9375     1.88235294 1.83333333]]
--------------
4.169526143790849


Создайте двумерный массив размером 3x8, заполненный числами от 1 до 24. 
Выполните суммирование по первой оси (axis=0), посчитайте среднее значение по второй оси. 
Выведите полученный результат.

In [59]:
x = np.arange(1, 25).reshape(3,8)
print(x)
print("--------------")
y = np.sum(x, axis=0)
print(y)
print("--------------")
z = np.sum(x, axis=1)
print(z)  
print("--------------") 
с = np.sum(x, axis=(0, 1))
print(с)
print("--------------") 
avg = np.mean(x, axis=1)
print(avg) 

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
--------------
[27 30 33 36 39 42 45 48]
--------------
[ 36 100 164]
--------------
300
--------------
[ 4.5 12.5 20.5]
