# <b><font color='teal'>Практикум 3</font></b>

### <font color='teal'>1. Анализ веб-логов</font>
Условия:<br>
Есть данные о посещениях сайта: каждая строка — пользователь, столбцы — дни недели (Пн–Вс).

Задачи:
1. Сгенерировать случайные данные о 10 пользователях сайта.
2. Найти пользователя, который посещал сайт чаще всего.
3. Найти день недели с максимальной посещаемостью.
4. Создать массив, где указано, сколько раз каждый пользователь посещал сайт больше 3 раз в день.

In [2]:
import numpy as np
np.random.seed(42)
days = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"]
print(days)
arr = np.random.randint(0, 6, size=(10, 7))
print(arr)
print("-------------------------------")
pt_user = np.sum(arr, axis=1)
print(f"User: {np.argmax(pt_user)} - {np.max(pt_user)} ")
print("-------------------------------")
pt_day = np.sum(arr, axis=0)
print(f"Day: {days[np.argmax(pt_day)]} - {np.max(pt_day)} ")
print("-------------------------------")
print(arr > 3) 
print("-------------------------------") 
pt_total = np.sum(arr > 3, axis=1)
print(f"Total: \n {pt_total[:, np.newaxis]}")
print("-------------------------------") 
new_gt_3_1 = pt_total.reshape(-1, 1)
print(new_gt_3_1)

['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс']
[[3 4 2 4 4 1 2]
 [2 2 4 3 2 5 4]
 [1 3 5 5 1 3 4]
 [0 3 1 5 4 3 0]
 [0 2 2 1 3 3 5]
 [5 5 2 3 3 0 2]
 [4 2 4 0 1 3 0]
 [3 5 1 1 0 1 4]
 [1 3 3 3 3 4 2]
 [5 0 3 1 3 1 5]]
-------------------------------
User: 1 - 22 
-------------------------------
Day: Вт - 29 
-------------------------------
[[False  True False  True  True False False]
 [False False  True False False  True  True]
 [False False  True  True False False  True]
 [False False False  True  True False False]
 [False False False False False False  True]
 [ True  True False False False False False]
 [ True False  True False False False False]
 [False  True False False False False  True]
 [False False False False False  True False]
 [ True False False False False False  True]]
-------------------------------
Total: 
 [[3]
 [3]
 [3]
 [2]
 [1]
 [2]
 [2]
 [2]
 [1]
 [2]]
-------------------------------
[[3]
 [3]
 [3]
 [2]
 [1]
 [2]
 [2]
 [2]
 [1]
 [2]]


### <font color='teal'>2. Продажа товаров со склада</font>
Условия:<br>
Компания управляет тремя складами, на которых хранятся три вида товаров: A, B, C.<br>
Количество товаров на складе (строки — склады, столбцы — товары):<br>
| Склад       | A   | B   | C  |
| ----------- | ----|-----|----|
| 1           | 50  | 30  | 20 |
| 2           | 40  | 50  | 30 |
| 3           | 60  | 20  | 40 |

Цена за единицу товара:<br>
- A — 10 евро
- B — 20 евро
- C — 15 евро<br>
Задачи:
1. Создать необходимую матрицу
2. Рассчитать, на какую сумму хранятся товары на каждом складе, и общую сумму всех товаров на складе
3. В день Х было куплено с каждого склада по 10 единиц каждого вида товара.
4. На следующий день остатки товара были проданы оптовому покупателю по заниженной стоимости. Известно, что с первого склада продали на сумму 560 евро, со второго - на 770 евро и с третьего - на 690 евро. За какую стоимость были проданы товары данному покупателю?

In [34]:
matrix = np.array([[50,30,20], [40,50,30], [60,20,40]])
price = np.array([10, 20, 15])
sum_matrix = matrix*price
print("SK: \n", sum_matrix)

print("-------------------------------")
total_sk = np.sum(sum_matrix, axis=1)
print(f"Total SK: {total_sk}")
total = np.sum(sum_matrix)
print(f"Total: {total}")
matrix_10 = matrix - 10
print("SK - 10: \n", matrix_10)
print("-------------------------------")
price = np.array([560, 770, 690])
print("Price: \n", price)
print("-------------------------------")
det = np.linalg.det(matrix_10)
print(f"Determinant: {det}")   
print("-------------------------------")
inv_matirx_10 = np.linalg.inv(matrix_10)
print("Inverse Matrix: \n", inv_matirx_10)
print("-------------------------------")
result = inv_matirx_10 @ price
print("Result: \n", result)



SK: 
 [[ 500  600  300]
 [ 400 1000  450]
 [ 600  400  600]]
-------------------------------
Total SK: [1400 1850 1600]
Total: 4850
SK - 10: 
 [[40 20 10]
 [30 40 20]
 [50 10 30]]
-------------------------------
Price: 
 [560 770 690]
-------------------------------
Determinant: 25000.0
-------------------------------
Inverse Matrix: 
 [[ 4.0000000e-02 -2.0000000e-02  4.4408921e-18]
 [ 4.0000000e-03  2.8000000e-02 -2.0000000e-02]
 [-6.8000000e-02  2.4000000e-02  4.0000000e-02]]
-------------------------------
Result: 
 [ 7. 10.  8.]


### <font color='teal'>3. Стоимость акций</font>
Пусть у вас есть данные о ежедневных изменениях стоимости акций компании в течение недели. Найдите изменение цены за каждый день, а также дни с минимальным и максимальным изменением. 
(Подсказка: Не забудьте, что когда вы ищите изменение в ценах, то кол-во значений уменьшается на 1, т.к. первое значение не с чем сравнивать.)

Пример вывода:<br>
Изменения цен за день: [ 5  5 -8 -4 17  5]<br>
Лучший день: суббота<br>
Худший день: четверг<br>

In [37]:
prices = np.array([100, 105, 110, 102, 98, 115, 120])
days = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"]

changes = []
for i in range(1, len(prices)):
    changes.append(int(prices[i] - prices[i-1]))
print("Изменения цен за день:", changes)

best_day_idx = np.argmax(changes) + 1
worst_day_idx = np.argmin(changes) + 1

print("Лучший день:", days[best_day_idx])
print("Худший день:", days[worst_day_idx])


Изменения цен за день: [5, 5, -8, -4, 17, 5]
Лучший день: Сб
Худший день: Чт


In [7]:
np.random.seed(42)
prices = np.random.randint(100, 110, size=7)
days = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"]
print("Цены на акции:", prices)
changes = np.diff(prices)
print("Изменения цен за день:", changes)
best_day_idx = np.argmax(changes) + 1
worst_day_idx = np.argmin(changes) + 1
abs_best_day_idx = np.argmax(abs(changes)) + 1
abs_worst_day_idx = np.argmin(abs(changes)) + 1
print("Лучший день:", days[best_day_idx])
print("Худший день:", days[worst_day_idx])
print("День с наибольшим абсолютным изменением:", days[abs_best_day_idx])
print("День с наименьшим абсолютным изменением:", days[abs_worst_day_idx])

Цены на акции: [106 103 107 104 106 109 102]
Изменения цен за день: [-3  4 -3  2  3 -7]
Лучший день: Ср
Худший день: Вс
День с наибольшим абсолютным изменением: Вс
День с наименьшим абсолютным изменением: Пт


Задайте  массив  grades  из  оценок  студентов  (оценки  от  0  до  100,  количество 
элементов – по количеству студентов в вашей группе). Напишите программу, которая 
увеличит все оценки на 10%.

In [6]:
grades = np.random.randint(0, 100, size=15)
grades_10 = grades * 1.1
print("Оценки студентов:", grades)
print("--------------------------------")
print("Оценки студентов с повышением на 10%:", grades_10) 

Оценки студентов: [73 61 99 13 94 47 14 71 77 86 61 39 84 79 81]
--------------------------------
Оценки студентов с повышением на 10%: [ 80.3  67.1 108.9  14.3 103.4  51.7  15.4  78.1  84.7  94.6  67.1  42.9
  92.4  86.9  89.1]


Задайте массив prices из цен на товары (цены от 1 до 100 евро, количество – не менее 
10). Сгенерируйте массив из булевых значений: False – для цен меньше 40 евро, True 
–  для  всех  остальных.  С его помощью сделайте скидку 5% для товаров с ценой не 
ниже 40.

In [5]:
prices = np.random.randint(1, 100, size=10)
print("Цены на акции:", prices)
print("--------------------------------")
prices_bool = prices >= 40
print("Цены на акции больше 40:", prices_bool)
print("--------------------------------")
skidka = (prices*prices_bool)*0.95
print(skidka)


Цены на акции: [ 6 54  4 54 93 63 18 90 44 34]
--------------------------------
Цены на акции больше 40: [False  True False  True  True  True False  True  True False]
--------------------------------
[ 0.   51.3   0.   51.3  88.35 59.85  0.   85.5  41.8   0.  ]


Пять спортсменов участвовали в соревновании, в котором нужно было бежать 2 часа, 
плыть 1 час и ехать на велосипеде 5 часов. 

Первый спортсмен бежал со скоростью 15 км/ч, плыл со скоростью 4 км/ч и ехал на 
велосипеде со скоростью 25 км/ч.

Соответствующие скорости второго спортсмена: 14 км/ч, 5 км/ч, 27 км/ч. 

Третий спортсмен: 16 км/ч, 5 км/ч, 23 км/ч. 

Четвертый: 13 км/ч, 5.5 км/ч, 26 км/ч. 

Пятый: 12 км/ч, 4.5 км/ч, 30 км/ч. 

Побеждает  тот,  кто  преодолел  большее  расстояние.  
Напишите  программу,  которая 
определяет победителя. 

Подсказка:  Подумайте,  что  здесь  можно  записать  матрицей,  что  вектором,  какая 
матричная операция определяет пройденное расстояние.) 

In [4]:
par = np.array([2, 1, 5])
print("Параметры:", par)
user = np.array([[15, 4, 25], 
                [16,  5, 23], 
                [13, 5.5, 26],
                [12, 4.5, 30]], dtype=float)
total = np.sum(user * par, axis=1)
print("Результат умножения параметров на данные пользователя: \n", total)

Параметры: [2 1 5]
Результат умножения параметров на данные пользователя: 
 [159.  152.  161.5 178.5]


Сделайте срез матрицы из предыдущей задачи, чтобы получить квадратную матрицу 
(т.е.  оставляем  только  трех  спортсменов).  

Сгенерируйте  случайный  столбец  трех чисел  от  100  до  200.  Будем  считать,  
что  это  расстояния,  пройденные  каждым спортсменом.  

Найдите  определитель  полученной  матрицы  и  матрицу,  обратную  к 
ней.  
Умножьте  обратную  матрицу  на  случайный  столбец  (с  помощью  матричного 
умножения). Поясните, что вы нашли с помощью такой операции. 

In [8]:
user_1 = user[:3]
print(user_1)
print("--------------------------------")
s = np.random.randint(100 , 110, size=3).reshape(-1, 1)
print("Случайные числа для умножения с результатом: \n", s)
print("--------------------------------")
det = np.linalg.det(user_1)
print(f"Детерминант: {det}")
print("--------------------------------")
inv_user_1  = np.linalg.inv(user_1)
print("Обратная матрица: \n", inv_user_1)
print("--------------------------------")
res = inv_user_1 @ s
print("Результат умножения обратной матрицы на вектор случайных чисел: \n", res)

[[15.   4.  25. ]
 [16.   5.  23. ]
 [13.   5.5 26. ]]
--------------------------------
Случайные числа для умножения с результатом: 
 [[106]
 [107]
 [104]]
--------------------------------
Детерминант: 159.49999999999994
--------------------------------
Обратная матрица: 
 [[ 0.02194357  0.21003135 -0.20689655]
 [-0.73354232  0.40752351  0.34482759]
 [ 0.14420063 -0.19122257  0.06896552]]
--------------------------------
Результат умножения обратной матрицы на вектор случайных чисел: 
 [[3.28213166]
 [1.71159875]
 [1.9968652 ]]


Транспонируйте матрицу из задачи 4. Поясните смысл каждой строки новой матрицы. 
На  вектор  какого  размера  ее  можно  умножить (дайте ответ для вектора-столбца и 
вектора-строки,  для  поэлементного  умножения  и  для  матричного  умножения). 
Объясните практический смысл каждой операции