# <b><font color='teal'>Математические операции над NumPy массивами</font></b>

### <font color='teal'>1. Базовые операции</font>

#### <font color='teal'>1.1. Для списков</font>

In [1]:
import numpy as np
two_d_list = [[1, 2, 3], [4, 5, 6]]
#Сложение списков
#Ваш код

In [ ]:
#Умножение списка на число
#Ваш код

#### <font color='teal'>1.2. Для массивов</font>
Размеры массивов для таких операций должны быть одинаковыми!

In [2]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
two_d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
#Сложение массивов
print(two_d_array + two_d_array)
#Ваш код

[[ 2  4  6]
 [ 8 10 12]]


In [4]:
#Умножение массивов
print(two_d_array * two_d_array)
#Ваш код

[[ 1  4  9]
 [16 25 36]]


In [5]:
#Умножение массива на число
print(two_d_array * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [6]:
#Прибавление числа к массиву
print(two_d_array + 2)

[[3 4 5]
 [6 7 8]]


In [7]:
#Демонстрация ошибки
square = np.array([[1, 2], [4, 5]])
print(square)
print(two_d_array + square)

[[1 2]
 [4 5]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [8]:
#Расширение матрицы по строкам
one_d_array = np.array([10, 20, 30])
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(one_d_array)
print(two_d_array)

[10 20 30]
[[1 2 3]
 [4 5 6]]


In [9]:
print(one_d_array + two_d_array)

[[11 22 33]
 [14 25 36]]


In [10]:
#Расширение матрицы по столбцам
col = np.array([[10], [20]])
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(col)
print(two_d_array)

[[10]
 [20]]
[[1 2 3]
 [4 5 6]]


In [11]:
print(col + two_d_array)

[[11 12 13]
 [24 25 26]]


#### <font color='teal'>1.3. Объединение массивов</font>

In [12]:
row = np.array([1, 2])
one_d_array = np.array([3, 4, 5])
print(np.concatenate( [row, one_d_array] ))

[1 2 3 4 5]


#### <font color='teal'>1.4. Задание для закрепления</font>
Что будет выведено в следующих случаях?

In [13]:
col = np.array([[10], [20], [30]])
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(col + two_d_array)

ValueError: operands could not be broadcast together with shapes (3,1) (2,3) 

In [14]:
mult = np.array([10, 20, 30])
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(mult)
print(two_d_array)
print(mult * two_d_array)

[10 20 30]
[[1 2 3]
 [4 5 6]]
[[ 10  40  90]
 [ 40 100 180]]


### <font color='teal'>2. Другие математические операции</font>

In [15]:
a = np.array([0, 2, 1])
b = np.array([3, 4, 5])

In [16]:
#Вычитание
print(a - b)

[-3 -2 -4]


In [17]:
#Деление
print(a / b)

[0.  0.5 0.2]


In [18]:
#Возведение в степень
print(a ** 2)

[0 4 1]


In [19]:
#Деление на 0
print(b / a)

[inf  2.  5.]


C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_17472\3466977691.py:2: RuntimeWarning: divide by zero encountered in divide
  print(b / a)


In [20]:
print(type((b / 0)[0]))

<class 'numpy.float64'>


C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_17472\644549865.py:1: RuntimeWarning: divide by zero encountered in divide
  print(type((b / 0)[0]))


In [21]:
np.inf == (b / 0)[0]

C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_17472\2711307984.py:1: RuntimeWarning: divide by zero encountered in divide
  np.inf == (b / 0)[0]


np.True_

In [22]:
print(np.array([-1])/0)

[-inf]


C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_17472\3965095333.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.array([-1])/0)


In [23]:
print(np.array([1])/-0.)

[-inf]


C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_17472\394153032.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.array([1])/-0.)


In [24]:
print(np.array([0])/0)

[nan]


C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_17472\3875527719.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array([0])/0)


In [25]:
print(np.array([np.inf])/np.inf)

[nan]


C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_17472\2842275430.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array([np.inf])/np.inf)


In [26]:
print(np.array([np.inf])/0)

[inf]


In [27]:
print(np.inf / 0)

ZeroDivisionError: float division by zero

In [28]:
print(0 / np.inf)

0.0


In [29]:
print(np.nan + 1, np.inf + 1, np.inf * 0, 1. / np.inf)

nan inf nan 0.0


### <font color='teal'>3. Сравнения, различные встроенные функции</font>

In [30]:
#Синус
a = np.array([0, 2, 1])
print(np.sin, type(np.sin))
print(np.sin(a))

<ufunc 'sin'> <class 'numpy.ufunc'>
[0.         0.90929743 0.84147098]


In [31]:
#Сравнения
a = np.array([0, 2, 1])
b = np.array([3, 2, 5])

In [32]:
print(a > b)

[False False False]


In [33]:
print(a == b)

[False  True False]


In [34]:
c = a >= 2
print(c)

[False  True False]


In [36]:
#Any возвращает True, если хотя бы один элемент в массиве True
print(np.any(c))

True


In [37]:
#All возвращает True, если все элементы в массиве True
print(np.all(c))

False


In [38]:
#Модификация на месте
b *= 2
print(b)

[ 6  4 10]


In [ ]:
#Различные статистические функции
a = np.array([2, 1, 4, 5, 6])
#Сумма всех элементов массива
# char.chararray.sum(axis=None, dtype=None, out=None, *, keepdims=<no value>, initial=<no value>, where=<no value>)
np.sum(a)
#Произведение всех элементов массива
# char.chararray.prod(axis=None, dtype=None, out=None, *, keepdims=<no value>, initial=<no value>, where=<no value>)
np.prod(a)
#Максимальный и минимальный элементы массива
# char.chararray.max(axis=None, out=None, *, keepdims=<no value>, initial=<no value>, where=<no value>)
np.max(a)
# char.chararray.min(axis=None, out=None, *, keepdims=<no value>, initial=<no value>, where=<no value>)
np.min(a)
#Среднее арифметическое элементов массива
# char.chararray.mean(axis=None, dtype=None, out=None, *, keepdims=<no value>, where=<no value>)
np.mean(a)
np.average(a)
#Среднеквадартичное отклонение элементов массива
# char.chararray.std(axis=None, dtype=None, out=None, ddof=0, *, keepdims=<no value>, where=<no value>, mean=<no value>)
np.std(a)

np.float64(1.8547236990991407)

In [45]:
print(np.sum(a))
print(np.prod(a))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.average(a))
print(np.std(a))

18
240
6
1
3.6
3.6
1.8547236990991407


In [40]:
#Немного полезных функций и констант
print(np.sqrt(b))
print(np.exp(b))
print(np.log(b))
print(np.sin(b))
print(np.e, np.pi)

[2.44948974 2.         3.16227766]
[  403.42879349    54.59815003 22026.46579481]
[1.79175947 1.38629436 2.30258509]
[-0.2794155  -0.7568025  -0.54402111]
2.718281828459045 3.141592653589793


In [46]:
#Кумулятивные суммы
print(b.cumsum())

[ 6 10 20]


#### <font color='teal'>3.1. Упражнение</font>
1) Создайте массив из 20 чисел от  −2𝜋  до  2𝜋.
2) Посчитайте поэлементные квадраты косинусов для данного массива.
3) С помощью np.all проверьте, что в ответе только числа не больше единицы.

In [58]:
#Ваше решение
arr_2 = np.linspace(-2*np.pi, 2*np.pi, 20)
print(arr_2)
print("-"*80)
arr_3 = np.cos(arr_2)**2
arr_4= pow(np.cos(arr_2), 2)
print(arr_3)
print("-"*80)
print(arr_4)
print("-"*80)
print(np.all(arr_2 <= 1))
print(np.all(arr_3 <= 1))

[-6.28318531 -5.62179738 -4.96040945 -4.29902153 -3.6376336  -2.97624567
 -2.31485774 -1.65346982 -0.99208189 -0.33069396  0.33069396  0.99208189
  1.65346982  2.31485774  2.97624567  3.6376336   4.29902153  4.96040945
  5.62179738  6.28318531]
--------------------------------------------------------------------------------
[1.         0.62274274 0.06026312 0.16135921 0.77347408 0.97290862
 0.45871033 0.00681935 0.29915229 0.89457025 0.89457025 0.29915229
 0.00681935 0.45871033 0.97290862 0.77347408 0.16135921 0.06026312
 0.62274274 1.        ]
--------------------------------------------------------------------------------
[1.         0.62274274 0.06026312 0.16135921 0.77347408 0.97290862
 0.45871033 0.00681935 0.29915229 0.89457025 0.89457025 0.29915229
 0.00681935 0.45871033 0.97290862 0.77347408 0.16135921 0.06026312
 0.62274274 1.        ]
--------------------------------------------------------------------------------
False
True


### <font color='teal'>4. Решение задач</font>

1) Что будет выведено в следующих случаях и почему?

In [59]:
cube = np.array(
    [
        [[1, 2], [3, 4]], 
        [[5, 6], [7, 8]]
     ]
    )
print(cube * cube)


[[[ 1  4]
  [ 9 16]]

 [[25 36]
  [49 64]]]


In [ ]:
print(cube + np.array(
                        [[10, 20], 
                         [30, 40]]
                         )
    )

[[[11 22]
  [33 44]]

 [[15 26]
  [37 48]]]


In [ ]:
print(cube + np.array(
                        [[10, 20]]
                        ))

[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]


In [62]:
print(cube + np.array([10, 20]))

[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]


In [ ]:
print(cube + np.array(
                        [[10], 
                         [20]]))

[[[11 12]
  [23 24]]

 [[15 16]
  [27 28]]]


2) Создание и изучение массивов
   <p> Создайте массив 4x4 со значениями от 0 до 15. Выведите: </p>
   <p>- Умножьте исходный массив на его третью строку </p>
   <p> - Вычтите из исходного массива второй столбец </p>

In [72]:
arr_4_4 = np.array([[0, 1, 2, 3],
                    [4, 5, 6, 7],   
                    [8, 9, 10, 11],
                    [12, 13, 14, 15]])
print(arr_4_4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [74]:
arr_4_1 = np.array([8, 9, 10, 11])
print(arr_4_1*arr_4_4)
print("-"*80)
print(arr_4_4*arr_4_4[2])

[[  0   9  20  33]
 [ 32  45  60  77]
 [ 64  81 100 121]
 [ 96 117 140 165]]
--------------------------------------------------------------------------------
[[  0   9  20  33]
 [ 32  45  60  77]
 [ 64  81 100 121]
 [ 96 117 140 165]]


In [80]:
arr_2_4 = np.array([1, 5, 9, 13])
print(arr_4_4-arr_2_4)
print("-"*80)
print(arr_4_4-np.array([arr_4_4[0][1], arr_4_4[1][1], arr_4_4[2][1], arr_4_4[3][1]]))

[[ -1  -4  -7 -10]
 [  3   0  -3  -6]
 [  7   4   1  -2]
 [ 11   8   5   2]]
--------------------------------------------------------------------------------
[[ -1  -4  -7 -10]
 [  3   0  -3  -6]
 [  7   4   1  -2]
 [ 11   8   5   2]]


3) Обработка крайних случаев
   <p> Что выведет код ниже? </p>

In [76]:
print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))

[  0.  nan  inf -inf]


C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_17472\3088186758.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))
C:\Users\Vitaliy\AppData\Local\Temp\ipykernel_17472\3088186758.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))
