# <b><font color='teal'>Практикум</font></b>

### <font color='teal'>Задание 1</font>
Напишите программу, которая:
- Запрашивает у пользователя ввод двух списков (list1, list2) – в первом 5 элементов, во втором 4. Списки вводятся в виде чисел, разделенных пробелами.
- Объединяет введенные списки в один новый список (list_full) из 9 элементов.
- Преобразует полученный список в массив (arr) NumPy.
- Трансформирует одномерный массив в матрицу размера 3х3. Обозначим эту матрицу Х.
- Выводит полученную матрицу.

In [10]:
import numpy as np
#Запрашиваем у пользователя ввод двух списков
list1 = map(int, input("Введите список из 5 чисел: ").split())
list2 = map(int, input("Введите список из 4 чисел: ").split())
#Объединяем введенные списки в один новый список
combined_list = list(list1) + list(list2)
 
#Преобразуем полученный список в массив NumPy.
array = np.array(combined_list)

#Трансформируем одномерный массив в матрицу размера 3х3
x = array.reshape(3, 3)

#Выводим полученную матрицу.
print(x)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## <font color='teal'>Задание 2</font>
Продолжение предыдущей задачи. Далее она:
- В каждой строке и в каждом столбце находит среднее, максимум, минимум, сумму, произведение.
- Для всей матрицы находит среднее, максимум, минимум, сумму, произведение и след.
- Выводит транспонированную матрицу для матрицы Х.

In [13]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
st_avg = np.mean(x, axis=1)
print("Среднее значение по строкам:", st_avg)
st_max = np.max(x, axis=1)
print("Максимальное значение по строкам:", st_max)
st_min = np.min(x, axis=1)
print("Минимальное значение по строкам:", st_min)
st_sum = np.sum(x, axis=1)
print("Сумма по строкам:", st_sum)
st_prod = np.prod(x, axis=1)
print("Произведение по строкам:", st_prod)
print("--------------")
stl_avg = np.mean(x, axis=0)
print("Среднее значение по столбцам:", stl_avg)
stl_max = np.max(x, axis=0)
print("Максимальное значение по столбцам:", stl_max)
stl_min = np.min(x, axis=0)
print("Минимальное значение по столбцам:", stl_min)
stl_sum = np.sum(x, axis=0)
print("Сумма по столбцам:", stl_sum)
stl_prod = np.prod(x, axis=0)
print("Произведение по столбцам:", stl_prod)
print("--------------")
all_avg = np.mean(x)
print("Среднее значение всех элементов:", all_avg)
all_max = np.max(x)
print("Максимальное значение всех элементов:", all_max)
all_min = np.min(x)
print("Минимальное значение всех элементов:", all_min)
all_sum = np.sum(x)
print("Сумма всех элементов:", all_sum)
all_prod = np.prod(x)
print("Произведение всех элементов:", all_prod)
x = np.trace(x)
print("Сумма элементов главной диагонали:", x)



Среднее значение по строкам: [2. 5. 8.]
Максимальное значение по строкам: [3 6 9]
Минимальное значение по строкам: [1 4 7]
Сумма по строкам: [ 6 15 24]
Произведение по строкам: [  6 120 504]
--------------
Среднее значение по столбцам: [4. 5. 6.]
Максимальное значение по столбцам: [7 8 9]
Минимальное значение по столбцам: [1 2 3]
Сумма по столбцам: [12 15 18]
Произведение по столбцам: [ 28  80 162]
--------------
Среднее значение всех элементов: 5.0
Максимальное значение всех элементов: 9
Минимальное значение всех элементов: 1
Сумма всех элементов: 45
Произведение всех элементов: 362880
Сумма элементов главной диагонали: 15


In [19]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
for i in range(0,len(x)):
    print()
    print(f'Row {i} Mean {x[i].mean()}')
    print(f'Column {i} Mean {x[:,i].mean()}')
    print(f'Row {i} Max {x[i].max()}')
    print(f'Column {i} Max {x[:,i].max()}')
    print(f'Row {i} Min {x[i].min()}')
    print(f'Column {i} Min {x[:,i].min()}')
    print(f'Row {i} Sum {x[i].sum()}')
    print(f'Column {i} Sum {x[:,i].sum()}')
    print(f'Row {i} Multiply {x[i].prod()}')
    print(f'Column {i} Multiply {x[:,i].prod()}')

    print("\n")
    print(f'Для всей матрицы Mean - {x.mean()}')
    print(f'Для всей матрицы Max - {x.max()}')
    print(f'Для всей матрицы Min - {x.min()}')
    print(f'Для всей матрицы Sum - {x.sum()}')
    print(f'Для всей матрицы Multiply - {x.prod()}')
    print(f'Для всей матрицы След - {x.trace()}')
    print("\n")

xt = x.T

print(f'Transponed - \n{xt}')


Row 0 Mean 2.0
Column 0 Mean 4.0
Row 0 Max 3
Column 0 Max 7
Row 0 Min 1
Column 0 Min 1
Row 0 Sum 6
Column 0 Sum 12
Row 0 Multiply 6
Column 0 Multiply 28


Для всей матрицы Mean - 5.0
Для всей матрицы Max - 9
Для всей матрицы Min - 1
Для всей матрицы Sum - 45
Для всей матрицы Multiply - 362880
Для всей матрицы След - 15



Row 1 Mean 5.0
Column 1 Mean 5.0
Row 1 Max 6
Column 1 Max 8
Row 1 Min 4
Column 1 Min 2
Row 1 Sum 15
Column 1 Sum 15
Row 1 Multiply 120
Column 1 Multiply 80


Для всей матрицы Mean - 5.0
Для всей матрицы Max - 9
Для всей матрицы Min - 1
Для всей матрицы Sum - 45
Для всей матрицы Multiply - 362880
Для всей матрицы След - 15



Row 2 Mean 8.0
Column 2 Mean 6.0
Row 2 Max 9
Column 2 Max 9
Row 2 Min 7
Column 2 Min 3
Row 2 Sum 24
Column 2 Sum 18
Row 2 Multiply 504
Column 2 Multiply 162


Для всей матрицы Mean - 5.0
Для всей матрицы Max - 9
Для всей матрицы Min - 1
Для всей матрицы Sum - 45
Для всей матрицы Multiply - 362880
Для всей матрицы След - 15


Transponed - 
[[1 4 7

### <font color='teal'>Задание 3</font>
Продолжение предыдущей задачи. Далее она:
- Генерирует массив из трех случайных элементов. Этот вектор-строку обозначим А.
- Трансформирует вектор-строку в вектор-столбец. Его обозначим B.
- Матрицу Х умножает на вектор-строку А.
- Матрицу Х умножает на вектор-столбец B.
- Выполняет матричное умножение матриц из предыдущих пунктов.

In [22]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
A = np.empty(3, int)
print(A)
print("--------------")
B = np.vstack(A) 
print(B)
print("--------------")
x_1 = x * A
print(x_1)
print("--------------")
x_2 = x * B
print(x_2)
print("--------------")
matrix_x = x_1 @ x_2
print(matrix_x)

[4598811712191092244 4578699642918806144 4605124381371868752]
--------------
[[4598811712191092244]
 [4578699642918806144]
 [4605124381371868752]]
--------------
[[ 4598811712191092244  9157399285837612288 -4631370929593945360]
 [  -51497224945182640  4446754140884479104  9184002214521660896]
 [-4701806162081457524  -263891004068654080  4552631284927715536]]
--------------
[[ 4598811712191092244  9197623424382184488 -4650308937136274884]
 [ -131945502034327040  4446754140884479104  9025453783803285248]
 [-4657617477816021968   -52493096444153216  4552631284927715536]]
--------------
[[-4613468137346810224 -5278556649137784032 -5943645160928757840]
 [ 8811858714867032128 -1558791526090244992  6517302306662029504]
 [ 3790441493371322864  2160973596957294048   531505700543265232]]


### <font color='teal'>Задание 4</font>
Продолжение предыдущей задачи. Далее она:
- Запрашивает у пользователя число i от 0 до 2.
- Выводит строку i из матрицы Х.
- Выводит столбец i из матрицы Х.

In [21]:
i = input("Введите число от 1 до 2: ")
i = int(i)
print("Строка i:", x[i])
print("Столбец i:", x[:, i])

Строка i: [7 8 9]
Столбец i: [3 6 9]


### <font color='teal'>Задание 5</font>
Создайте матрицу A 5х5 из чисел от 1 до 25. Из этой матрицы извлеките две подматрицы: С размера 2х3 из левого верхнего угла исходной матрицы, и В размера 3х2 из правого нижнего угла исходной матрицы. Найдите матричное произведение С на B и B на С.

In [ ]:
A_1 = np.arange(1,26).reshape(5, 5)
print("Исходная матрица A:")
print(A_1)
print("--------------")
C = A_1[:2, :3]
print("Подматрица C (2x3):")
print(C)
print("--------------")
B = A_1[2:, 3:]
print("Подматрица B (3x2):")
print(B)
print("--------------")
CB = C @ B
print("C @ B = ")
print(CB)
print("--------------")
BC = B @ C
print("B @ C = ")
print(BC)

Исходная матрица A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
--------------
Подматрица C (2x3):
[[1 2 3]
 [6 7 8]]
--------------
Подматрица B (3x2):
[[14 15]
 [19 20]
 [24 25]]
--------------
C @ B = 
[[124 130]
 [409 430]]
--------------
B @ C = 
[[104 133 162]
 [139 178 217]
 [174 223 272]]


### <font color='teal'>Задание 6</font>
Запросите у пользователя ввод трех чисел – x, y, z. Создайте трехмерный массив (arr_3_d) размера x*y*z и заполните его числами от 10 до 20 с подходящим шагом. Выведите его. Запросите у пользователя координаты элемента (i, j, k) этого тензора и его новое значение (new_element). Замените выбранный элемент на новое значение.
Вычислите среднее, максимум, минимум, сумму, произведение по каждой оси.

In [33]:
x, y, z = map(int, input("Введите размеры массива (x y z): ").split())

arr_3_d = np.linspace(10, 20, num=x*y*z).reshape(x, y, z)
print("Трёхмерный массив:")
print(arr_3_d)

i = int(input(f"Введите i (от 0 до {x-1}): "))
j = int(input(f"Введите j (от 0 до {y-1}): "))
k = int(input(f"Введите k (от 0 до {z-1}): "))
new_element = float(input("Введите новое значение: "))
arr_3_d[i, j, k] = new_element
print("\nМассив после замены:")
print(arr_3_d)

# Ось 0
print("\nОсь 0:")
print("Среднее:")
print(arr_3_d.mean(axis=0))
print("----------")
print("Максимум:")
print(arr_3_d.max(axis=0))
print("----------")
print("Минимум:")
print(arr_3_d.min(axis=0))
print("----------")
print("Сумма:")
print(arr_3_d.sum(axis=0))
print("----------")
print("Произведение:")
print(arr_3_d.prod(axis=0))

# Ось 1
print("\nОсь 1:")
print("Среднее:")
print(arr_3_d.mean(axis=1))
print("----------")
print("Максимум:")
print(arr_3_d.max(axis=1))
print("----------")
print("Минимум:")
print(arr_3_d.min(axis=1))
print("----------")
print("Сумма:")
print(arr_3_d.sum(axis=1))
print("----------")
print("Произведение:")
print(arr_3_d.prod(axis=1))

# Ось 2
print("\nОсь 2:")
print("Среднее:")
print(arr_3_d.mean(axis=2))
print("----------")
print("Максимум:")
print(arr_3_d.max(axis=2))
print("----------")
print("Минимум:")
print(arr_3_d.min(axis=2))
print("----------")
print("Сумма:")
print(arr_3_d.sum(axis=2))
print("----------")
print("Произведение:")
print(arr_3_d.prod(axis=2))

Трёхмерный массив:
[[[10.         10.90909091 11.81818182]
  [12.72727273 13.63636364 14.54545455]]

 [[15.45454545 16.36363636 17.27272727]
  [18.18181818 19.09090909 20.        ]]]

Массив после замены:
[[[10.         10.90909091 11.81818182]
  [12.72727273 13.63636364 14.54545455]]

 [[15.45454545 16.36363636 17.27272727]
  [18.18181818 19.09090909  8.        ]]]

Ось 0:
Среднее:
[[12.72727273 13.63636364 14.54545455]
 [15.45454545 16.36363636 11.27272727]]
----------
Максимум:
[[15.45454545 16.36363636 17.27272727]
 [18.18181818 19.09090909 14.54545455]]
----------
Минимум:
[[10.         10.90909091 11.81818182]
 [12.72727273 13.63636364  8.        ]]
----------
Сумма:
[[25.45454545 27.27272727 29.09090909]
 [30.90909091 32.72727273 22.54545455]]
----------
Произведение:
[[154.54545455 178.51239669 204.1322314 ]
 [231.40495868 260.33057851 116.36363636]]

Ось 1:
Среднее:
[[11.36363636 12.27272727 13.18181818]
 [16.81818182 17.72727273 12.63636364]]
----------
Максимум:
[[12.7272727

### <font color='teal'>Задание 7</font>
Напишите программу, которая запрашивает у пользователя три числа (a, b, c) и создает трехмерный массив A соответствующей размерности, заполненный случайными числами. Выведите массив на экран.

In [34]:
a, b, c = map(int, input("Введите размеры массива (a b c): ").split())
A = np.empty([a,b,c,], dtype=int)
print("Исходный массив A:")
print(A)

Исходный массив A:
[[[                   0      140704782328000                   70
   -1932782235145732123]
  [                -216                    0                    0
      34058609623827524]
  [    9007723242848300    27303540894466109    30962698412359792
      29555009996456052]]

 [[   32651599816949870   302308600345395240   306812363249812533
     301745847960339509]
  [  306249400412013623   301745830780470347   302308763623294017
      33777169006068784]
  [   34340084605583392     9570286650916905    31525691315847209
      11259497291513964]]]
