# <b><font color='skyblue'>Numpy. Revision</font></b>

In [2]:
# Импорт библиотек
import numpy as np

### <b><font color='skyblue'>1. Создание массивов</font></b>

##### <b><u><font color='skyblue'>Синтаксис</font></b></u>
<b> numpy.array(object, dtype = None, copy = True, order = 'K', ndmin = 0) </b>
- <b> object</b> - входные данные, обычно список или кортеж.
- <b> dtype</b> - желаемый тип данных массива (необязательно).
- <b> copy</b> - если True (по умолчанию), объект копируется. Если False, копирование производится только в случае необходимости.
- <b> order</b> - порядок расположения в памяти ('C' для row-major, 'F' для column-major, 'A' - как в исходном объекте, 'K' - как в исходных данных в памяти).
- <b> ndmin</b> - указывает минимальное количество измерений, которое должен иметь результирующий массив.

In [3]:
# Демонстрация dtype
a = np.array([1, 2, 3, 4, 5], dtype = 'str')
a

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [4]:
# Демонстрация copy = True/False
a = np.array([1, 2, 3, 4, 5], dtype = 'float')
b = np.array(a, copy = False)
b[0] = 10
a, b

(array([10.,  2.,  3.,  4.,  5.]), array([10.,  2.,  3.,  4.,  5.]))

In [5]:
# Демонстрация ndmin
a = np.array([1,2,3], ndmin = 3)
print(a.shape)
a

(1, 1, 3)


array([[[1, 2, 3]]])

In [6]:
# Создание одномерного массива из списка
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)
print("Массив из списка:", array_from_list)

Массив из списка: [1 2 3 4 5]


In [7]:
# Создание одномерного массива из кортежа
tuple_data = (6, 7, 8, 9, 10)
array_from_tuple = np.array(tuple_data)
print("Массив из кортежа:", array_from_tuple)

Массив из кортежа: [ 6  7  8  9 10]


In [8]:
# Создание двумерного массива из списка списков
list_of_lists = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(list_of_lists)
print("Двумерный массив из списка списков:\n", array_2d)

Двумерный массив из списка списков:
 [[1 2 3]
 [4 5 6]]


### <b><font color='skyblue'>2. Атрибуты массивов</font></b>

##### <b><font color='skyblue'>Атрибут ndim</font></b>
Возвращает количество измерений (осей) массива

In [9]:
# Создание одномерного массива
array1 = np.array([1, 2, 3])
print(array1.ndim)

1


In [10]:
# Создание двумерного массива
array2 = np.array([[2, 3, 4], [5, 6, 7]])
print(array2.ndim)

2


##### <b><font color='skyblue'>Атрибут shape</font></b>
Возвращает кортеж целых чисел, указывающих размер массива в каждом измерении.

In [11]:
# Создание одномерного массива
array1 = np.array([1, 2, 3])
print(array1.shape)

(3,)


In [12]:
# Создание двумерного массива
array2 = np.array([[3, 4, 5], [6, 7, 8]])
print(array2.shape)

(2, 3)


##### <b><font color='skyblue'>Атрибут size</font></b>
Возвращает общее количество элементов в массиве

In [13]:
# Создание одномерного массива
array1 = np.array([1, 2, 3])
print(array1.size)

3


In [14]:
# Создание двумерного массива
array2 = np.array([[3, 5, 7], [8, 9, 10]])
print(array2.size)

6


##### <b><font color='skyblue'>Атрибут dtype</font></b>
Возвращает тип данных элементов массива

In [15]:
# Создание массива целых чисел
array1 = np.array([10, 20, 30])
print(array1.dtype)

int64


In [16]:
# Создание массива строк
array2 = np.array(["Python", "NumPy", "Data"])
print(array2.dtype)

<U6


In [17]:
array2[0] = 'Assembler'
array2

array(['Assemb', 'NumPy', 'Data'], dtype='<U6')

In [18]:
array2_copy = np.append(array2,['Fortran', 'Assembler'])
array2_copy

array(['Assemb', 'NumPy', 'Data', 'Fortran', 'Assembler'], dtype='<U9')

##### <b><font color='skyblue'>Атрибут itemsize</font></b>
Возвращает размер (в байтах) каждого элемента в массиве

In [19]:
# Создание массива 64-битных целых чисел
array1 = np.array([1, 2, 3], dtype = np.int64)
print(array1.itemsize)

8


In [20]:
# Создание массива 32-битных целых чисел
array2 = np.array([1, 2, 3], dtype = np.int32)
print(array2.itemsize)

4


### <b><font color='skyblue'>3. Шаблоны массивов</font></b>

##### <u><b><font color='skyblue'>np.zeros()</font></b></u>
Создает массив, заполненный нулями

In [21]:
# Создание одномерного массива нулей
array1 = np.zeros(5)
print("1D массив нулей:", array1)

1D массив нулей: [0. 0. 0. 0. 0.]


In [22]:
# Создание двумерного массива нулей
array2 = np.zeros((3, 4))
print("Двумерный массив нулей:\n", array2)

Двумерный массив нулей:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##### <b><font color='skyblue'>np.ones()</font></b>
Создает массив, заполненный единицами

In [23]:
# Создание одномерного массива единиц
array1 = np.ones(5)
print("одномерный массив единиц:", array1)

одномерный массив единиц: [1. 1. 1. 1. 1.]


In [24]:
# Создание двумерного массива единиц
array2 = np.ones((3, 4))
print("Двумерный массив единиц:\n", array2)

Двумерный массив единиц:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


##### <b><font color='skyblue'>np.full()</font></b>
Создает массив, заполненный заданным значением

In [25]:
# Создание одномерного массива, заполненного значением 7
array1 = np.full(5, 7)
print("Одномерный массив, заполненный значением 7:", array1)

Одномерный массив, заполненный значением 7: [7 7 7 7 7]


In [26]:
# Создание двумерного массива, заполненного значением 3,14
array2 = np.full((3, 4), 3.14)
print("Двумерный массив, заполненный значением 3.14:\n", array2)

Двумерный массив, заполненный значением 3.14:
 [[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]


### <b><font color='skyblue'>4. Создание последовательностей</font></b>

##### <b><font color='skyblue'>np.arange()</font></b>
Генерирует массив с равномерно распределенными значениями в заданном диапазоне

<b> numpy.arange([start, ]stop, [step, ]dtype = None)</b>
- <b>start</b>: Начальное значение последовательности (включительно). По умолчанию равно 0.
- <b>stop</b>: Конечное значение последовательности (включительно).
- <b>step (шаг)</b>: Расстояние между значениями. По умолчанию равно 1.
- <b>dtype (тип)</b>: Желаемый тип данных массива (необязательно).

In [27]:
# Создание массива со значениями от 0 до 9
array1 = np.arange(10)
print("Массив со значениями от 0 до 9:", array1)

Массив со значениями от 0 до 9: [0 1 2 3 4 5 6 7 8 9]


In [28]:
# Создание массива со значениями от 1 до 9
array2 = np.arange(1, 10)
print("Массив со значениями от 1 до 9:", array2)

Массив со значениями от 1 до 9: [1 2 3 4 5 6 7 8 9]


In [29]:
# Создание массива со значениями от 1 до 9 с шагом 2
array3 = np.arange(1, 10, 2)
print("Массив со значениями от 1 до 9 с шагом 2:", array3)

Массив со значениями от 1 до 9 с шагом 2: [1 3 5 7 9]


In [30]:
# Создание массива со значениями с плавающей точкой
array4 = np.arange(0, 1, 0.1)
print("Массив со значениями с плавающей точкой от 0 до 1 с шагом 0,1:", array4)

Массив со значениями с плавающей точкой от 0 до 1 с шагом 0,1: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


##### <b><font color='skyblue'>np.linspace()</font></b>
Генерирует массив с заданным количеством равномерно распределенных значений в заданном интервале

<b> numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False)</b>
- <b>start</b>: Начальное значение последовательности (включительно). По умолчанию равно 0.
- <b>stop</b>: Конечное значение последовательности (включительно).
- <b>num</b>: Количество равномерно распределенных образцов для генерации. По умолчанию 50
- <b>endpoint</b>: Если True (по умолчанию), то stop - это последний образец. Если False, то он не включается.
- <b>retstep</b>: Если True, возвращает размер шага между выборками.

In [31]:
# Создание массива с 10 равномерно распределенными значениями от 0 до 1
array1 = np.linspace(0, 1, 10)
print("Массив с 10 равномерно распределенными значениями от 0 до 1:", array1)

Массив с 10 равномерно распределенными значениями от 0 до 1: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [32]:
# Создание массива с 5 равномерно распределенными значениями от 1 до 10
array2 = np.linspace(1, 10, 5)
print("Массив с 5 равномерно распределенными значениями от 1 до 10:", array2)

Массив с 5 равномерно распределенными значениями от 1 до 10: [ 1.    3.25  5.5   7.75 10.  ]


In [33]:
# Создание массива с 5 равномерно распределенными значениями от 1 до 10, исключая конечную точку
array3 = np.linspace(1, 10, 5, endpoint = False)
print("Массив с 5 равномерно распределенными значениями от 1 до 10, исключая конечную точку:", array3)

Массив с 5 равномерно распределенными значениями от 1 до 10, исключая конечную точку: [1.  2.8 4.6 6.4 8.2]


In [34]:
# Создание массива и возвращение размера шага
array4, step = np.linspace(0, 1, 5, retstep = True)
print("Массив с 5 равномерно расположенными значениями от 0 до 1:", array4)
print("Размер шага:", step)

Массив с 5 равномерно расположенными значениями от 0 до 1: [0.   0.25 0.5  0.75 1.  ]
Размер шага: 0.25


### <b><font color='skyblue'>5. Арифметические операции в NumPy</font></b>

#### <b><font color='skyblue'>5.1. Поэлементные операции</font></b>
Поэлементные операции в NumPy - это операции, которые применяются к каждому соответствующему элементу массивов.

##### <b><font color='skyblue'>Сложение</font></b>

In [35]:
# Способ 1
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b
print(result)

[5 7 9]


In [36]:
# Способ 2
result = np.add(a, b)
print(result)

[5 7 9]


##### <b><font color='skyblue'>Вычитание</font></b>

In [37]:
# Способ 1
result = a - b
print(result)

[-3 -3 -3]


In [38]:
# Способ 2
result = np.subtract(a, b)
print(result)

[-3 -3 -3]


##### <b><font color='skyblue'>Умножение</font></b>

In [39]:
# Способ 1
result = a * b
print(result)

[ 4 10 18]


In [40]:
# Способ 2
result = np.multiply(a, b)
print(result)

[ 4 10 18]


##### <b><font color='skyblue'>Деление</font></b>

In [41]:
# Способ 1
result = a / b
print(result)

[0.25 0.4  0.5 ]


In [42]:
# Способ 2
result = np.divide(a, b)
print(result)

[0.25 0.4  0.5 ]


##### <b><font color='skyblue'>Возведение в степень</font></b>

In [43]:
# Способ 1
result= a ** b
print(result)

[  1  32 729]


In [44]:
# Способ 2
result = np.power(a, b)
print(result)

[  1  32 729]


#### <b><u><font color='skyblue'>5.2. Broadcasting - трансляция</font></b></u>
Позволяет выполнять арифметические операции над массивами различной формы<br>
<i>Правила broadcasting’а:</i>
- Массивы совместимы для broadcasting’а, если для каждой размерности их размеры либо одинаковы, либо один из них равен 1.
- Результирующая форма массива - это максимальный размер по каждому измерению входных массивов.

In [45]:
# Массив a формы (3, 1)
a = np.array([[1], [2], [3]])

In [46]:
# Массив b формы (1, 4)
b = np.array([4, 5, 6, 7])

In [47]:
# Передача a и b в форму (3, 4)
result = a + b
print(result)

[[ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


In [48]:
result = a ** b
print(result)

[[   1    1    1    1]
 [  16   32   64  128]
 [  81  243  729 2187]]


### <b><font color='skyblue'>6. Операции над матрицами</font></b>

#### <b><font color='skyblue'>6.1. Умножение матриц</font></b>
<b>np.dot(), np.matmul(), @</b><br>
Количество столбцов в первой матрице должно быть равно количеству строк во второй матрице.

In [49]:
# Создание двух матриц
matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6]])
matrix1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
# Умножение матриц
result = np.dot(matrix1, matrix2)
print("Матричное умножение:\n", result)

Матричное умножение:
 [[ 9 12 15]
 [19 26 33]
 [29 40 51]]


#### <b><font color='skyblue'>6.2. Транспонирование матрицы</font></b>
<b>np.transpose(), .T</b><br>
Транспонирование матрицы получается, если поменять местами ее строки и столбцы.

In [51]:
# Создание матрицы
matrix = np.array([[1, 3], [5, 7]])
matrix

array([[1, 3],
       [5, 7]])

In [52]:
# Транспонирование матрицы
transpose = np.transpose(matrix)
print("Транспонирование:\n", transpose)

Транспонирование:
 [[1 5]
 [3 7]]


### <b><font color='skyblue'>7. Изменение формы и размера массивов</font></b>

##### <b><font color='skyblue'>reshape()</font></b>
Изменяет форму массива, не изменяя его данных. Общее количество элементов должно оставаться неизменным.

In [53]:
# 1D в 2D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print("От 1D к 2D:\n", newarr)

От 1D к 2D:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [54]:
# 1D в 3D
newarr = arr.reshape(2, 3, 2)
print("От 1D к 3D:\n", newarr)

От 1D к 3D:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [55]:
# Использование -1 для неизвестной размерности
newarr = arr.reshape(2, 2, -1)
print("Использование -1 для неизвестной размерности:\n", newarr)

Использование -1 для неизвестной размерности:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


##### <b><font color='skyblue'>resize()</font></b>
Изменяет форму массива и может изменять общее количество элементов. Если новый размер больше, массив заполняется повторяющимися копиями исходных данных.

In [56]:
# Исходный массив
arr = np.array([[0, 1], [2, 3]])
arr

array([[0, 1],
       [2, 3]])

In [57]:
# Изменение размера массива в большую сторону
resized_arr = np.resize(arr, (2, 3))
print("Изменен размер массива на больший:\n", resized_arr)

Изменен размер массива на больший:
 [[0 1 2]
 [3 0 1]]


In [58]:
# Изменение размера массива в меньшую сторону
resized_arr = np.resize(arr, (1, 4))
print("Изменен размер массива на меньший:\n", resized_arr)

Изменен размер массива на меньший:
 [[0 1 2 3]]


##### <b><font color='skyblue'>newaxis()</font></b>
Используется для увеличения размерности массива еще на одно измерение

In [59]:
# Исходный одномерный массив
arr = np.array([1, 2, 3])

In [60]:
# Добавление новой оси
newarr = arr[:, np.newaxis]
print("Добавление новой оси с помощью np.newaxis:\n", newarr)

Добавление новой оси с помощью np.newaxis:
 [[1]
 [2]
 [3]]


### <b><font color='skyblue'>8. Случайные числа в NumPy</font></b>

#### <b><font color='skyblue'>8.1. Генерация случайных чисел</font></b>

##### <b><font color='skyblue'>np.random.rand()</font></b>
Генерирует случайные числа из равномерного распределения на интервале [0, 1)

In [61]:
# Генерация одного случайного числа
random_number = np.random.rand()
print("Одиночное случайное число:", random_number)

Одиночное случайное число: 0.3705865097471728


In [62]:
# Генерация одномерного массива случайных чисел
random_array_1d = np.random.rand(5)
print("Одномерный массив случайных чисел:", random_array_1d)

Одномерный массив случайных чисел: [0.48350326 0.94586645 0.08893967 0.744449   0.77359785]


In [63]:
# Генерация двумерного массива случайных чисел
random_array_2d = np.random.rand(3, 4)
print("Двумерный массив случайных чисел:\n", random_array_2d)

Двумерный массив случайных чисел:
 [[0.19642565 0.33233901 0.29164345 0.7172007 ]
 [0.26959944 0.88717346 0.10546288 0.58470094]
 [0.34449548 0.74238671 0.39328319 0.3385968 ]]


##### <b><font color='skyblue'>np.random.randn()</font></b>
Генерирует случайные числа из стандартного нормального распределения (среднее = 0, стандартное отклонение = 1)

In [64]:
# Генерация одного случайного числа из стандартного нормального распределения
random_number = np.random.randn()
print("Одиночное случайное число из стандартного нормального распределения:", random_number)

Одиночное случайное число из стандартного нормального распределения: -1.6870265933907829


In [65]:
# Генерация одномерного массива случайных чисел из стандартного нормального распределения
random_array_1d = np.random.randn(5)
print("1D массив случайных чисел из стандартного нормального распределения:", random_array_1d)

1D массив случайных чисел из стандартного нормального распределения: [ 0.98286698 -0.78248437  1.75418177 -0.27343816  0.55225265]


In [66]:
# Генерирование двумерного массива случайных чисел из стандартного нормального распределения
random_array_2d = np.random.randn(3, 4)
print("Двумерный массив случайных чисел из стандартного нормального распределения:\n", random_array_2d)

Двумерный массив случайных чисел из стандартного нормального распределения:
 [[ 0.92194684 -0.17603445  0.08513029  0.09727868]
 [ 0.12336532  0.98626335  0.5373581  -0.30688379]
 [ 0.05180066  1.02256081 -0.08247531  0.14813146]]


##### <b><font color='skyblue'>np.random.randint()</font></b>
Генерирует случайные целые числа из заданного диапазона

<b>numpy.random.randint(low, high = None, size = None, dtype = int)</b>
- <b>low:</b> Наименьшее целое число (включительно).
- <b>high:</b> Наибольшее целое число (включительно). Если None, то диапазон будет [0, low).
- <b>size:</b> Форма возвращаемого массива (необязательно).
- <b>dtype:</b> Желаемый тип данных массива (необязательно, по умолчанию int)

In [67]:
# Генерация одного случайного целого числа
random_int = np.random.randint(10)
print("Одиночное случайное целое число:", random_int)

Одиночное случайное целое число: 0


In [118]:
# Генерация одномерного массива случайных целых чисел
random_array_1d = np.random.randint(1, 10,10)
print("1D массив случайных целых чисел:", random_array_1d)

1D массив случайных целых чисел: [7 4 9 3 5 3 7 5 9 7]


In [69]:
# Генерирование двумерного массива случайных целых чисел
random_array_2d = np.random.randint(1, 10, (3, 4))
print("Двумерный массив случайных целых чисел:\n", random_array_2d)

Двумерный массив случайных целых чисел:
 [[2 5 5 1]
 [9 7 2 9]
 [7 9 6 9]]


#### <b><font color='skyblue'>8.2. Случайная выборка</font></b>
Генерирует случайную выборку из заданного одномерного массива.<br>
<b>numpy.random.choice(a, size = None, replace = True, p = None)</b>
- <b>a:</b> Входной массив или диапазон.
- <b>size:</b> Форма возвращаемого массива (необязательно).
- <b>replace:</b> Выборка с повторениями или без повторений (по умолчанию True).
- <b>p:</b> Вероятности, связанные с каждой записью в a (необязательно).

In [70]:
# Создание массива
arr = np.array([1, 2, 3, 4, 5])

In [71]:
# Случайный выбор одного элемента
random_choice = np.random.choice(arr)
print("Случайно выбранный элемент:", random_choice)

Случайно выбранный элемент: 1


In [72]:
# Случайный выбор нескольких элементов с заменой
random_choices = np.random.choice(arr, size = 3, replace = True)
print("Случайно выбранные элементы с повторением:", random_choices)

Случайно выбранные элементы с повторением: [1 3 5]


In [73]:
# Случайный выбор нескольких элементов без замены
random_choices = np.random.choice(arr, size = 3, replace = False)
print("Случайный выбор элементов без повторений:", random_choices)

Случайный выбор элементов без повторений: [4 1 3]


In [88]:
# Случайный выбор элементов с заданными вероятностями
random_choices = np.random.choice(arr, size = 3, p = [0.1, 0.2, 0.3, 0.2, 0.2])
print("Случайно выбранные элементы с заданными вероятностями:", random_choices)

Случайно выбранные элементы с заданными вероятностями: [2 3 3]


#### <b><font color='skyblue'>8.3. Воспроизводимость</font></b>
Установка seed обеспечивает воспроизводимость генерируемых случайных чисел, что важно для отладки и обмена результатами.

In [90]:
# Установка семени
np.random.seed(42) # здесь может быть любое число

In [111]:
# Генерация случайных чисел
np.random.seed(42)
random_array_1 = np.random.rand(10)
print("Случайный массив 1:", random_array_1)

Случайный массив 1: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]


In [94]:
# Сброс затравки
np.random.seed(42)

In [106]:
# Снова генерируем случайные числа
random_array_2 = np.random.rand(10)
print("Случайный массив 2:", random_array_2)

Случайный массив 2: [0.07455064 0.98688694 0.77224477 0.19871568 0.00552212 0.81546143
 0.70685734 0.72900717 0.77127035 0.07404465]


### <b><font color='skyblue'>9. Решение задач</font></b>

##### <b><font color='skyblue'>Задача 1</font></b>
Создайте одномерный массив, преобразуйте его в двумерный, а затем “сплющите” обратно в одномерный.

In [112]:
# Создайте одномерный массив чисел от 1 до 12 в переменную array_1d
array_1d = np.arange(1, 13)
print("Одномерный массив от 1 до 12:", array_1d)

Одномерный массив от 1 до 12: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [113]:
# Преобразуйте его в двумерный array_2d
array_2d = array_1d.reshape(4, 3)
print("Двумерный массив 4x3:\n", array_2d)

Двумерный массив 4x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [114]:
# С помощью функции flatten преобразуйте двумерный массив в одномерный flattened_array
flattened_array = array_2d.flatten()
print("Плоский массив:\n", flattened_array)

Плоский массив:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


##### <b><font color='skyblue'>Задача 2</font></b>
Сгенерируйте случайный массив и рассчитайте <u>базовую статистику</u>.

In [115]:
# Создайте массив random_array размером 4х5 из случайных чисел
random_array = np.random.randint(50,500,(4,5))
print("Массив случайных чисел 4x5:\n", random_array)

Массив случайных чисел 4x5:
 [[199 358 307 393 463]
 [343 435 241 493 326]
 [210 363  71 302 285]
 [394  98 108 219 237]]


In [116]:
# Рассчитайте:
# среднее значение в переменную mean_value
# стандартное отклонение в переменную std_value
# минимальное значение в переменную min_value
# максимальное значение в переменную max_value
mean_value = np.mean(random_array)
std_value = np.std(random_array)
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Среднее значение:", mean_value)
print("Стандартное отклонение:", std_value)
print("Минимальное значение:", min_value)
print("Максимальное значение:", max_value)

Среднее значение: 292.25
Стандартное отклонение: 116.37949776485547
Минимальное значение: 71
Максимальное значение: 493
