# <b><font color='lightcoral'>Тип данных Pandas.DataFrame</font></b>

### <font color='lightcoral'>1. Создание DataFrame</font>

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Способ №1 - из словаря
dict_for_df = {'col1': [1, 2], 'col2': ['a', 'b']}
dict_for_df

{'col1': [1, 2], 'col2': ['a', 'b']}

In [4]:
df_from_dict = pd.DataFrame(dict_for_df)
df_from_dict

,col1,col2
0,1,a
1,2,b


In [5]:
# Способ №2 - из словаря с использованием объекта Series
dict_for_df = {'col2': pd.Series([5, 6], index = [0, 1]),'col1': [0, 1, 2, 3], }
dict_for_df

{'col2': 0    5
 1    6
 dtype: int64,
 'col1': [0, 1, 2, 3]}

In [6]:
df_from_dict = pd.DataFrame(dict_for_df, index=[0, 1, 2, 3])
df_from_dict

,col2,col1
0,5.0,0
1,6.0,1
2,NaN,2
3,NaN,3


In [7]:
# Способ №3 - из массива
import numpy as np
arr_for_df = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_for_df

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
df_from_array = pd.DataFrame(arr_for_df, columns = ['a', 'b', 'c'])
df_from_array

,a,b,c
0,1,2,3
1,4,5,6
2,7,8,9


In [9]:
# Способ №4 - из нескольких Series
ser_1 = pd.Series([1, 2, 3, 4])
ser_2 = pd.Series(['a', 'b', 'c', 'd'])
df_from_series = pd.DataFrame(pd.concat([ser_1, ser_2], axis = 1))
df_from_series

,0,1
0,1,a
1,2,b
2,3,c
3,4,d


In [10]:
arr = np.ones((5,5))
print(arr)
print("----------------------------")
df_empty = pd.DataFrame(arr)
print(df_empty)
print("----------------------------")
print(df_empty.size)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
----------------------------
     0    1    2    3    4
0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0  1.0
----------------------------
25


In [11]:
# Способ №5 - из файла!!! Самый популярный
df_from_file = pd.read_csv('../data/titanic.csv')
df_from_file

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000


In [12]:
# Разная длина series
d = {'one': pd.Series(range(6), index=list('abdefg')),
     'two': pd.Series(range(7), index=list('abcdefg')),
     'three': pd.Series(np.random.normal(size=7), index=list('abcdefg'))}
df = pd.DataFrame(d)
df

,one,two,three
a,0.0,0,-0.904995
b,1.0,1,0.430572
c,NaN,2,0.957021
d,2.0,3,-1.057926
e,3.0,4,0.570798
f,4.0,5,-0.914521
g,5.0,6,-1.049971


### <font color='lightcoral'>2. Анализ DataFrame</font>

In [13]:
#Просмотр начала таблицы
df_from_file.head(3)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250


In [14]:
#Просмотр конца таблицы
df_from_file.tail(3)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.45
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.00
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.75


In [15]:
#Просмотр индексов
df_from_file.index

RangeIndex(start=0, stop=887, step=1)

In [16]:
#Просмотр колонок (столбцов)
df_from_file.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Siblings/Spouses Aboard',
       'Parents/Children Aboard', 'Fare'],
      dtype='object')

In [17]:
#Получение данных - результат array
df_from_file.values

array([[0, 3, 'Mr. Owen Harris Braund', ..., 1, 0, 7.25],
       [1, 1, 'Mrs. John Bradley (Florence Briggs Thayer) Cumings', ...,
        1, 0, 71.2833],
       [1, 3, 'Miss. Laina Heikkinen', ..., 0, 0, 7.925],
       ...,
       [0, 3, 'Miss. Catherine Helen Johnston', ..., 1, 2, 23.45],
       [1, 1, 'Mr. Karl Howell Behr', ..., 0, 0, 30.0],
       [0, 3, 'Mr. Patrick Dooley', ..., 0, 0, 7.75]],
      shape=(887, 8), dtype=object)

In [18]:
#Описательные характеристики
df_from_file.describe()

,Survived,Pclass,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
count,887.000000,887.000000,887.000000,887.000000,887.000000,887.00000
mean,0.385569,2.305524,29.471443,0.525366,0.383315,32.30542
std,0.487004,0.836662,14.121908,1.104669,0.807466,49.78204
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.00000
25%,0.000000,2.000000,20.250000,0.000000,0.000000,7.92500
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.45420
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.13750
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.32920


In [19]:
df_from_file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Survived                 887 non-null    int64  
 1   Pclass                   887 non-null    int64  
 2   Name                     887 non-null    object 
 3   Sex                      887 non-null    object 
 4   Age                      887 non-null    float64
 5   Siblings/Spouses Aboard  887 non-null    int64  
 6   Parents/Children Aboard  887 non-null    int64  
 7   Fare                     887 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.6+ KB


In [20]:
# Транспонирование данных
df_from_file.T

,0,1,2,3,4,5,6,7,8,9,...,877,878,879,880,881,882,883,884,885,886
Survived,0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,1,0
Pclass,3,1,3,1,3,3,1,3,3,2,...,3,3,2,3,3,2,1,3,1,3
Name,Mr. Owen Harris Braund,Mrs. John Bradley (Florence Briggs Thayer) Cum...,Miss. Laina Heikkinen,Mrs. Jacques Heath (Lily May Peel) Futrelle,Mr. William Henry Allen,Mr. James Moran,Mr. Timothy J McCarthy,Master. Gosta Leonard Palsson,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,Mrs. Nicholas (Adele Achem) Nasser,...,Mr. Johann Markun,Miss. Gerda Ulrika Dahlberg,Mr. Frederick James Banfield,Mr. Henry Jr Sutehall,Mrs. William (Margaret Norton) Rice,Rev. Juozas Montvila,Miss. Margaret Edith Graham,Miss. Catherine Helen Johnston,Mr. Karl Howell Behr,Mr. Patrick Dooley
Sex,male,female,female,female,male,male,male,male,female,female,...,male,female,male,male,female,male,female,female,male,male
Age,22.0,38.0,26.0,35.0,35.0,27.0,54.0,2.0,27.0,14.0,...,33.0,22.0,28.0,25.0,39.0,27.0,19.0,7.0,26.0,32.0
Siblings/Spouses Aboard,1,1,0,1,0,0,0,3,0,1,...,0,0,0,0,0,0,0,1,0,0
Parents/Children Aboard,0,0,0,0,0,0,0,1,2,0,...,0,0,0,0,5,0,0,2,0,0
Fare,7.25,71.2833,7.925,53.1,8.05,8.4583,51.8625,21.075,11.1333,30.0708,...,7.8958,10.5167,10.5,7.05,29.125,13.0,30.0,23.45,30.0,7.75


In [21]:
# Сортировка по столбцу
df_from_file.sort_values(by = 'Age', ascending = False)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
627,1,1,Mr. Algernon Henry Wilson Barkworth,male,80.00,0,0,30.0000
847,0,3,Mr. Johan Svensson,male,74.00,0,0,7.7750
95,0,1,Mr. George B Goldschmidt,male,71.00,0,0,34.6542
490,0,1,Mr. Ramon Artagaveytia,male,71.00,0,0,49.5042
115,0,3,Mr. Patrick Connors,male,70.50,0,0,7.7500
...,...,...,...,...,...,...,...,...
827,1,2,Master. George Sibley Richards,male,0.83,1,1,18.7500
466,1,3,Miss. Helene Barbara Baclini,female,0.75,2,1,19.2583
641,1,3,Miss. Eugenie Baclini,female,0.75,2,1,19.2583
751,1,2,Master. Viljo Hamalainen,male,0.67,1,1,14.5000


In [22]:
df_from_file.sort_values(by = ['Age', 'Pclass'])

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
799,1,3,Master. Assad Alexander Thomas,male,0.42,0,1,8.5167
751,1,2,Master. Viljo Hamalainen,male,0.67,1,1,14.5000
466,1,3,Miss. Helene Barbara Baclini,female,0.75,2,1,19.2583
641,1,3,Miss. Eugenie Baclini,female,0.75,2,1,19.2583
77,1,2,Master. Alden Gates Caldwell,male,0.83,0,2,29.0000
...,...,...,...,...,...,...,...,...
115,0,3,Mr. Patrick Connors,male,70.50,0,0,7.7500
95,0,1,Mr. George B Goldschmidt,male,71.00,0,0,34.6542
490,0,1,Mr. Ramon Artagaveytia,male,71.00,0,0,49.5042
847,0,3,Mr. Johan Svensson,male,74.00,0,0,7.7750


##### <font color='lightcoral'>2.1. Задача</font>

<b>Дано:</b><br>
У вас есть информация о продажах в интернет-магазине:
- Товары: ['Ноутбук', 'Смартфон', 'Планшет', 'Наушники', 'Смарт-часы']
- Цена: [75000, 30000, 20000, 5000, 12000]
- Продано единиц: [120, 340, 150, 500, 230]

Задания:
1. Создайте DataFrame удобным для Вас способом (из Series, из файла, из словаря, из списка списков). Подумайте, как лучше организовать данные: что будет индексами, что будет колонками, что будет в данных.
2. Отсортируйте данные тремя способами:
- По цене (возрастание).
- По количеству проданных единиц (убывание).
- По выручке (Цена × Продано единиц) — в порядке убывания.
3. Найдите ТОП-3 товара по выручке и выведите их в отдельный DataFrame.

In [23]:
products = ['Ноутбук', 'Смартфон', 'Планшет', 'Наушники', 'Смарт-часы']
prices = [75000, 30000, 20000, 5000, 12000]
Quantity = [120, 340, 150, 500, 230]
data = {'Product': products, 'Price': prices, 'Quantity': Quantity}
df_products = pd.DataFrame(data)
print(df_products)
print("----------------------------")
df_products_sorted = df_products.sort_values(by = ['Price', 'Quantity'], ascending = [True, False])
print(df_products_sorted)
print("----------------------------")
df_products['Revenue'] = df_products['Price'] * df_products['Quantity']
df_products_sorted = df_products.sort_values(by = ['Revenue'], ascending = False)
print(df_products_sorted)
print("----------------------------")
df_products_top3 = df_products.sort_values(by = ['Revenue'], ascending = False).head(3)
print(df_products_top3)

      Product  Price  Quantity
0     Ноутбук  75000       120
1    Смартфон  30000       340
2     Планшет  20000       150
3    Наушники   5000       500
4  Смарт-часы  12000       230
----------------------------
      Product  Price  Quantity
3    Наушники   5000       500
4  Смарт-часы  12000       230
2     Планшет  20000       150
1    Смартфон  30000       340
0     Ноутбук  75000       120
----------------------------
      Product  Price  Quantity   Revenue
1    Смартфон  30000       340  10200000
0     Ноутбук  75000       120   9000000
2     Планшет  20000       150   3000000
4  Смарт-часы  12000       230   2760000
3    Наушники   5000       500   2500000
----------------------------
    Product  Price  Quantity   Revenue
1  Смартфон  30000       340  10200000
0   Ноутбук  75000       120   9000000
2   Планшет  20000       150   3000000


### <font color='lightcoral'>3. ндексация в DataFrame</font>

In [24]:
# Если в качестве индекса указать имя столбца, получится одномерный набор данных типа Series.
ser_from_df = pd.Series(df_from_file['Name'])
ser_from_df

0                                 Mr. Owen Harris Braund
1      Mrs. John Bradley (Florence Briggs Thayer) Cum...
2                                  Miss. Laina Heikkinen
3            Mrs. Jacques Heath (Lily May Peel) Futrelle
4                                Mr. William Henry Allen
                             ...                        
882                                 Rev. Juozas Montvila
883                          Miss. Margaret Edith Graham
884                       Miss. Catherine Helen Johnston
885                                 Mr. Karl Howell Behr
886                                   Mr. Patrick Dooley
Name: Name, Length: 887, dtype: object

In [25]:
#Выбрать несколько столбцов
df_from_file[['Name', 'Age', 'Sex']]

,Name,Age,Sex
0,Mr. Owen Harris Braund,22.0,male
1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,38.0,female
2,Miss. Laina Heikkinen,26.0,female
3,Mrs. Jacques Heath (Lily May Peel) Futrelle,35.0,female
4,Mr. William Henry Allen,35.0,male
...,...,...,...
882,Rev. Juozas Montvila,27.0,male
883,Miss. Margaret Edith Graham,19.0,female
884,Miss. Catherine Helen Johnston,7.0,female
885,Mr. Karl Howell Behr,26.0,male


In [26]:
# К столбцу можно обращаться как к полю объекта, если имя столбца позволяет это сделать (= является строкой)
df_from_file['Siblings/Spouses Aboard']

0      1
1      1
2      0
3      1
4      0
      ..
882    0
883    0
884    1
885    0
886    0
Name: Siblings/Spouses Aboard, Length: 887, dtype: int64

In [27]:
# ндексы полученного одномерного набора данных.
df_from_file.Name.index

RangeIndex(start=0, stop=887, step=1)

In [28]:
# Можно получить имя данного столбца
df_from_file.Name.name

'Name'

In [29]:
# Получение элемента массива. Сначала надо указать столбец, потом строку 
df_from_file['Name'][5]

'Mr. James Moran'

In [30]:
#Получение среза
df_from_file[10:20] #правая граница не включается

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
10,1,3,Miss. Marguerite Rut Sandstrom,female,4.0,1,1,16.7000
11,1,1,Miss. Elizabeth Bonnell,female,58.0,0,0,26.5500
12,0,3,Mr. William Henry Saundercock,male,20.0,0,0,8.0500
13,0,3,Mr. Anders Johan Andersson,male,39.0,1,5,31.2750
14,0,3,Miss. Hulda Amanda Adolfina Vestrom,female,14.0,0,0,7.8542
15,1,2,Mrs. (Mary D Kingcome) Hewlett,female,55.0,0,0,16.0000
16,0,3,Master. Eugene Rice,male,2.0,4,1,29.1250
17,1,2,Mr. Charles Eugene Williams,male,23.0,0,0,13.0000
18,0,3,Mrs. Julius (Emelia Maria Vandemoortele) Vande...,female,31.0,1,0,18.0000
19,1,3,Mrs. Fatima Masselmani,female,22.0,0,0,7.2250


In [31]:
#Получение среза
d = {'one': pd.Series(range(6), index=list('abdefg')),
     'two': pd.Series(range(7), index=list('abcdefg')),
     'three': pd.Series(np.random.normal(size=7), index=list('abcdefg'))}
df = pd.DataFrame(d)
df

,one,two,three
a,0.0,0,1.215516
b,1.0,1,-0.046716
c,NaN,2,0.296229
d,2.0,3,0.242497
e,3.0,4,0.762899
f,4.0,5,-1.292066
g,5.0,6,1.682702


In [32]:
df['b':'e'] #правая граница включается

,one,two,three
b,1.0,1,-0.046716
c,NaN,2,0.296229
d,2.0,3,0.242497
e,3.0,4,0.762899


In [33]:
# Нельзя обращаться по индексу к строке
df_from_file[1]

KeyError: 1

In [ ]:
# Можно так
df_from_file[1:2]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833


In [ ]:
#Вывод с шагом
df_from_file[1:30:2]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
5,0,3,Mr. James Moran,male,27.0,0,0,8.4583
7,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.0750
9,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14.0,1,0,30.0708
11,1,1,Miss. Elizabeth Bonnell,female,58.0,0,0,26.5500
13,0,3,Mr. Anders Johan Andersson,male,39.0,1,5,31.2750
15,1,2,Mrs. (Mary D Kingcome) Hewlett,female,55.0,0,0,16.0000
17,1,2,Mr. Charles Eugene Williams,male,23.0,0,0,13.0000
19,1,3,Mrs. Fatima Masselmani,female,22.0,0,0,7.2250


In [ ]:
type(df_from_file['Age'])

pandas.core.series.Series

In [ ]:
type(df_from_file[['Age']])

pandas.core.frame.DataFrame

##### <font color='lightcoral'>3.1. loc, iloc</font>

In [ ]:
d = {'one': pd.Series(range(6), index=list('abdefg')),
     'two': pd.Series(range(7), index=list('abcdefg')),
     'three': pd.Series(np.random.normal(size=7), index=list('abcdefg'))}
df = pd.DataFrame(d)
df

,one,two,three
a,0.0,0,0.579465
b,1.0,1,-1.334697
c,NaN,2,0.145337
d,2.0,3,0.034797
e,3.0,4,2.664088
f,4.0,5,0.599890
g,5.0,6,0.198927


In [ ]:
df.loc['b']

one      1.000000
two      1.000000
three   -1.334697
Name: b, dtype: float64

In [ ]:
df.loc['b']['one']

np.float64(1.0)

In [ ]:
df['one']['b']

np.float64(1.0)

In [ ]:
df.loc['a':'b', 'one']

a    0.0
b    1.0
Name: one, dtype: float64

In [ ]:
df.loc['a':'b', :]

,one,two,three
a,0.0,0,0.579465
b,1.0,1,-1.334697


In [ ]:
df.loc[:, 'one']

a    0.0
b    1.0
c    NaN
d    2.0
e    3.0
f    4.0
g    5.0
Name: one, dtype: float64

In [ ]:
df.iloc[2]

one           NaN
two      2.000000
three    0.145337
Name: c, dtype: float64

In [ ]:
df.iloc[1:3]

,one,two,three
b,1.0,1,-1.334697
c,NaN,2,0.145337


In [ ]:
df.iloc[1:3, 0:2]

,one,two
b,1.0,1
c,NaN,2


In [ ]:
# Булевская индексация - выбор строк с заданным условием
df_from_file[df_from_file.Age > 70]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
95,0,1,Mr. George B Goldschmidt,male,71.0,0,0,34.6542
115,0,3,Mr. Patrick Connors,male,70.5,0,0,7.7500
490,0,1,Mr. Ramon Artagaveytia,male,71.0,0,0,49.5042
627,1,1,Mr. Algernon Henry Wilson Barkworth,male,80.0,0,0,30.0000
847,0,3,Mr. Johan Svensson,male,74.0,0,0,7.7750


In [ ]:
df_from_file[(df_from_file.Age > 30) & (df_from_file.Sex == 'male')]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
6,0,1,Mr. Timothy J McCarthy,male,54.0,0,0,51.8625
13,0,3,Mr. Anders Johan Andersson,male,39.0,1,5,31.2750
20,0,2,Mr. Joseph J Fynney,male,35.0,0,0,26.0000
21,1,2,Mr. Lawrence Beesley,male,34.0,0,0,13.0000
...,...,...,...,...,...,...,...,...
863,0,1,Mr. Washington Augustus II Roebling,male,31.0,0,0,50.4958
868,0,1,Mr. Frans Olof Carlsson,male,33.0,0,0,5.0000
869,0,3,Mr. Victor Vander Cruyssen,male,47.0,0,0,9.0000
877,0,3,Mr. Johann Markun,male,33.0,0,0,7.8958


In [ ]:
df_from_file[df_from_file['Name'].notna()]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000


### <font color='lightcoral'>4. Решение задач</font>

У вас есть датасет Titanic. Основные колонки: <br>
- Survived — факт выживания (0 — нет, 1 — да)
- Pclass — класс билета (1, 2, 3)
- Name — имя пассажира
- Sex — пол
- Age — возраст
- Siblings/Spouses Aboard — число родственников (братьев/сестёр/супругов) на борту
- Parents/Children Aboard — число родителей/детей на борту
- Fare — стоимость билета

Задания:
1. Выведите каждую 3-ю строку до 20-й включительно.
2. Отсортируйте пассажиров: 
- По возрасту (по возрастанию);
- По стоимости билета (Fare) в порядке убывания;
- По классу билета (Pclass) и возрасту одновременно.
3. С помощью .loc:
- Выберите имена и возраст всех женщин младше 18 лет.
4. С помощью .iloc:
- Получите данные 10-й строки (по позиции);
- Выведите первые 3 столбца для строк с 5-й по 10-ю.
5. спользуя булевы условия:
- Найдите всех пассажиров 1-го класса старше 50 лет.
- Сколько женщин выжило во 2-м классе?
- Постройте DataFrame только с пассажирами, у которых стоимость билета выше средней (Fare > mean).

In [ ]:
import pandas as pd

pd.set_option("display.width", None)
pd.set_option("display.max_columns", None)

# Загрузка датасета
df_titanic = pd.read_csv("../data/titanic.csv")
df_titanic.head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500


In [ ]:
# ЗАДАНЕ 1: каждая 3-я строка до 20-й включительно
# iloc[:20:3] — срез первых 20 строк с шагом 3
df_titanic.iloc[:20:3]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
6,0,1,Mr. Timothy J McCarthy,male,54.0,0,0,51.8625
9,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14.0,1,0,30.0708
12,0,3,Mr. William Henry Saundercock,male,20.0,0,0,8.0500
15,1,2,Mrs. (Mary D Kingcome) Hewlett,female,55.0,0,0,16.0000
18,0,3,Mrs. Julius (Emelia Maria Vandemoortele) Vande...,female,31.0,1,0,18.0000


In [ ]:
# ЗАДАНЕ 2.1: сортировка по возрасту (от младших к старшим)
sorted_by_age = df_titanic.sort_values(by="Age")
sorted_by_age

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
799,1,3,Master. Assad Alexander Thomas,male,0.42,0,1,8.5167
751,1,2,Master. Viljo Hamalainen,male,0.67,1,1,14.5000
641,1,3,Miss. Eugenie Baclini,female,0.75,2,1,19.2583
466,1,3,Miss. Helene Barbara Baclini,female,0.75,2,1,19.2583
77,1,2,Master. Alden Gates Caldwell,male,0.83,0,2,29.0000
...,...,...,...,...,...,...,...,...
115,0,3,Mr. Patrick Connors,male,70.50,0,0,7.7500
490,0,1,Mr. Ramon Artagaveytia,male,71.00,0,0,49.5042
95,0,1,Mr. George B Goldschmidt,male,71.00,0,0,34.6542
847,0,3,Mr. Johan Svensson,male,74.00,0,0,7.7750


In [ ]:
# ЗАДАНЕ 2.2: сортировка по стоимости билета (от дорогих к дешёвым)
sorted_by_fare_desc = df_titanic.sort_values(by="Fare", ascending=False)
sorted_by_fare_desc

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
257,1,1,Miss. Anna Ward,female,35.0,0,0,512.3292
676,1,1,Mr. Thomas Drake Martinez Cardeza,male,36.0,0,1,512.3292
733,1,1,Mr. Gustave J Lesurer,male,35.0,0,0,512.3292
339,1,1,Miss. Alice Elizabeth Fortune,female,24.0,3,2,263.0000
435,0,1,Mr. Mark Fortune,male,64.0,1,4,263.0000
...,...,...,...,...,...,...,...,...
802,0,1,Mr. Thomas Jr Andrews,male,39.0,0,0,0.0000
811,0,1,Mr. Richard Fry,male,39.0,0,0,0.0000
478,0,2,Mr. Anthony Wood Frost,male,37.0,0,0,0.0000
463,0,2,Mr. William Campbell,male,21.0,0,0,0.0000


In [ ]:
# ЗАДАНЕ 2.3: сортировка сначала по классу, потом по возрасту
sorted_by_class_age = df_titanic.sort_values(by=["Pclass", "Age"])
sorted_by_class_age

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
303,1,1,Master. Hudson Trevor Allison,male,0.92,1,2,151.5500
295,0,1,Miss. Helen Loraine Allison,female,2.00,1,2,151.5500
442,1,1,Master. Washington Dodge,male,4.00,0,2,81.8583
798,1,1,Master. William Thornton II Carter,male,11.00,1,2,120.0000
432,1,1,Miss. Lucile Polk Carter,female,14.00,1,2,120.0000
...,...,...,...,...,...,...,...,...
278,0,3,Mr. Frank Duane,male,65.00,0,0,7.7500
508,0,3,Mr. James Webber,male,66.00,0,0,8.0500
535,0,3,Mr. Samuel Beard Risien,male,69.00,0,0,14.5000
115,0,3,Mr. Patrick Connors,male,70.50,0,0,7.7500


In [ ]:
# ЗАДАНЕ 3: .loc — выбор по меткам
# Условие: пол == female  возраст < 18
# Выбираем только столбцы Name и Age
women_under_18 = df_titanic.loc[
    (df_titanic["Sex"] == "female") & (df_titanic["Age"] < 18),
    ["Name", "Age"]
]
women_under_18

,Name,Age
9,Mrs. Nicholas (Adele Achem) Nasser,14.0
10,Miss. Marguerite Rut Sandstrom,4.0
14,Miss. Hulda Amanda Adolfina Vestrom,14.0
22,Miss. Anna McGowan,15.0
24,Miss. Torborg Danira Palsson,8.0
...,...,...
848,Miss. Nourelain Boulos,9.0
849,Miss. Mary Conover Lines,16.0
859,Miss. Dorothy Edith Sage,14.0
871,Miss. Adele Kiamie Najib,15.0


In [ ]:
# ЗАДАНЕ 4.1: .iloc — выбор по позиции
# iloc[9] — 10-я строка (индексация с 0)
df_titanic.iloc[9]

Survived                                                    1
Pclass                                                      2
Name                       Mrs. Nicholas (Adele Achem) Nasser
Sex                                                    female
Age                                                      14.0
Siblings/Spouses Aboard                                     1
Parents/Children Aboard                                     0
Fare                                                  30.0708
Name: 9, dtype: object

In [ ]:
# ЗАДАНЕ 4.2: .iloc — срез строк и столбцов по позиции
# Строки 5–10 (iloc[4:10]) и первые 3 столбца (:3)
df_titanic.iloc[5:11, :3]

,Survived,Pclass,Name
5,0,3,Mr. James Moran
6,0,1,Mr. Timothy J McCarthy
7,0,3,Master. Gosta Leonard Palsson
8,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
9,1,2,Mrs. Nicholas (Adele Achem) Nasser
10,1,3,Miss. Marguerite Rut Sandstrom


In [ ]:
# ЗАДАНЕ 5.1: булево условие — 1-й класс  возраст > 50
first_class_over_50 = df_titanic[
    (df_titanic["Pclass"] == 1) & (df_titanic["Age"] > 50)
]
first_class_over_50

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
6,0,1,Mr. Timothy J McCarthy,male,54.0,0,0,51.8625
11,1,1,Miss. Elizabeth Bonnell,female,58.0,0,0,26.5500
53,0,1,Mr. Engelhart Cornelius Ostby,male,65.0,0,1,61.9792
63,0,1,Mr. Albert A Stewart,male,64.0,0,0,27.7208
95,0,1,Mr. George B Goldschmidt,male,71.0,0,0,34.6542
123,0,1,Mr. Percival Wayland White,male,54.0,0,1,77.2875
154,0,1,Mr. Charles Duane Williams,male,51.0,0,1,61.3792
167,0,1,Mr. John D Baumann,male,60.0,0,0,25.9250
169,0,1,Mr. Wyckoff Van der hoef,male,61.0,0,0,33.5000
173,0,1,Mr. James Clinch Smith,male,56.0,0,0,30.6958


In [ ]:
# ЗАДАНЕ 5.2: количество женщин, выживших во 2-м классе
# .shape[0] возвращает количество строк
survived_women_2nd = df_titanic[
    (df_titanic["Sex"] == "female") &
    (df_titanic["Pclass"] == 2) &
    (df_titanic["Survived"] == 1)
].shape[0]
print(survived_women_2nd)

70


In [ ]:
# ЗАДАНЕ 5.3: DataFrame пассажиров с Fare выше среднего
# Сначала считаем среднее, потом фильтруем
fare_mean = df_titanic["Fare"].mean()  # среднее значение стоимости билета
fare_above_mean_df = df_titanic[df_titanic["Fare"] > fare_mean]
fare_above_mean_df

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
6,0,1,Mr. Timothy J McCarthy,male,54.0,0,0,51.8625
23,1,1,Mr. William Thompson Sloper,male,28.0,0,0,35.5000
27,0,1,Mr. Charles Alexander Fortune,male,19.0,3,2,263.0000
...,...,...,...,...,...,...,...,...
852,1,1,Mrs. George Dennick (Mary Hitchcock) Wick,female,45.0,1,1,164.8667
859,0,3,Miss. Dorothy Edith Sage,female,14.0,8,2,69.5500
863,0,1,Mr. Washington Augustus II Roebling,male,31.0,0,0,50.4958
867,1,1,Mrs. Richard Leonard (Sallie Monypeny) Beckwith,female,47.0,1,1,52.5542
