# <b><font color='teal'>ндексация, начало работы с матрицами</font></b>

### <font color='teal'>1. Сортировка, изменение массивов</font>

In [1]:
#Подключение библиотеки NumPy
import numpy as np

In [2]:
b = np.array([6, 4, 10])
#Функция sort вернет отсортированную копию, т.е. массив b НЕ изменится
print("сходный массив ", b)
print("Отсортированный массив ",np.sort(b))
print("Массив после функции sort() ",b)
#Метод sort отсортриует сам массив, т.е. массив b изменится
b.sort()
print("Массив после метода sort() ",b)

сходный массив  [ 6  4 10]
Отсортированный массив  [ 4  6 10]
Массив после функции sort()  [ 6  4 10]
Массив после метода sort()  [ 4  6 10]


- <a href="https://numpy.org/devdocs/reference/generated/numpy.sort.html" target="_blank">Функция sort</a>
- <a href="https://numpy.org/devdocs/reference/generated/numpy.ndarray.sort.html#numpy.ndarray.sort" target="_blank">Метод sort</a>

In [5]:
#Удаление элементов массива
a = np.arange(1, 11)
print("сходный массив ", a)
#Функция delete НЕ изменяет массив
#Функция delete принимает 2 обязательных аргумента (первый - массив, в котором нужно удалить элемент, второй - индекс элемента, который нужно удалить)
a = np.delete(a, 5)
print("Массив после удаления элемента с индексом 5 ", a)

сходный массив  [ 1  2  3  4  5  6  7  8  9 10]
Массив после удаления элемента с индексом 5  [ 1  2  3  4  5  7  8  9 10]


- <a href="https://numpy.org/devdocs/reference/generated/numpy.delete.html#numpy.delete" target="_blank">Функция delete</a>

In [6]:
#Вставка элемента в центр массива
a = np.arange(1, 11)
print("сходный массив ", a)
#Функция insert НЕ изменяет массив
#Функция insert принимает 3 обязательных аргумента (первый - массив, в который нужно вставить элемент, 
#                                                  второй - индекс элемента, начиная с которого нужно вставить элементы,
#                                                  третий - элемент, который необходимо добавить)
a = np.insert(a, 2, [0, 0])
print("Массив после добавления элемента начиная с индекса 2 ", a)

сходный массив  [ 1  2  3  4  5  6  7  8  9 10]
Массив после добавления элемента начиная с индекса 2  [ 1  2  0  0  3  4  5  6  7  8  9 10]


- <a href="https://numpy.org/devdocs/reference/generated/numpy.insert.html#numpy-insert" target="_blank">Функция insert</a>

In [7]:
#Вставка элемента в конец массива
a = np.arange(1, 11)
print("сходный массив ", a)
#Функция append НЕ изменяет массив
#Функция append принимает 2 обязательных аргумента (первый - массив, в который нужно вставить элемент, 
#                                                  второй - элемент, который необходимо добавить)
a = np.append(a, [1, 2, 3])
print("Массив после добавления элемента в конец ", a)

сходный массив  [ 1  2  3  4  5  6  7  8  9 10]
Массив после добавления элемента в конец  [ 1  2  3  4  5  6  7  8  9 10  1  2  3]


- <a href="https://numpy.org/devdocs/reference/generated/numpy.append.html#numpy-append" target="_blank">Функция append</a>

### <font color='teal'>2. ндексация для доступа к данным</font>
В многомерных массивах для адресации используются индексы для каждого измерения.

In [8]:
#ндексация в одномерном массиве (векторе)
one_d_array = np.array([1, 2, 3])
#Вывод элемента с индексом 0
print(one_d_array[0])

1


In [9]:
#ндексация в двумерном массиве (матрице)
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
#Вывод строки с индексом 1
print(two_d_array[1])
#Вывод элемента на пересечениие строки с индексом 1 и столбцом с индексом 2
#Способ 1
print(two_d_array[1, 2])
#Способ 2
print(two_d_array[1][2])

[4 5 6]
6
6


In [4]:
#ндексация в трехмерном массиве
three_d_array = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print(three_d_array)
print("-"*20)
#Вывод элемента с индексом 0 в первой размерности
print(three_d_array[0])
print("-"*20)
#Вывод элемента с индексом 0 в первой размерности и с индексом 1 во второй размерности
print(three_d_array[0, 1])
print("-"*20)
#Вывод элемента с индексом 0 в первой размерности, с индексом 1 во второй размерности и с индексом 0 в третей размерности
print(three_d_array[0, 1, 0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
--------------------
[[1 2]
 [3 4]
 [5 6]]
--------------------
[3 4]
--------------------
3


<font color='red'>Массивы являются изменяемыми объектами! </font>

In [11]:
int_array = np.array([1, 2, 3])
print("сходный массив ", int_array)
int_array[2] = 5 
print("змененный массив ", int_array)

сходный массив  [1 2 3]
змененный массив  [1 2 5]


#### <font color='teal'>2.1. Срезы</font>

In [12]:
#Одномерный массив
one_d_array = np.array([1, 2, 3])
#Срез элементов с индексами от 0 до 1 включительно
print(one_d_array[0:2])

[1 2]


In [5]:
#Двумерный массив
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("сходный массив \n", two_d_array)
print("-"*20)
#Срез строк с индексами от 1 до 2 включительно и столбцов с индексами от 0 до 1 включительно
print(two_d_array[1:3, 0:2])

сходный массив 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------------
[[4 5]
 [7 8]]


In [19]:
#Трехмерный массив
three_d_array = np.array([[[1, 2], [1, 2], [3, 4]], [[5, 6], [7, 8], [9, 10]], [[11, 12], [13, 14], [15, 16]]])
print("сходный массив \n", three_d_array)
#Срез первых двух элементов, затем 2 и 3, и 1 и 2
print ('----------------')
print(three_d_array[0:2, 1:3, 0:1])


сходный массив 
 [[[ 1  2]
  [ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]]]
----------------
[[[1]
  [3]]

 [[7]
  [9]]]


In [7]:
#Срез первой строки
print(two_d_array)
print ('----------------')
print(two_d_array[0])
#Срез второго столбца
print(two_d_array[:, 1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------------
[1 2 3]
[ 2  5  8 11]


In [6]:
#Следующие две записи эквивалентны
print(two_d_array[0, :])
print(two_d_array[0])

[1 2 3]
[1 2 3]


In [8]:
#Срез массива - это view, экран, очки "старого" массива"
x = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
s = x[1:3]
print(s)
s[0] = 101
print(s)
print(x)
#Преимущество: не тратятся ресурсы на хранение среза. 
#Недостатки: ухудшается читаемость программы.

[2.2 3.3]
[101.    3.3]
[  1.1 101.    3.3   4.4   5.5]


In [11]:
#сравним со списками
list1 = [1, 2, 3, 4, 5, 6]
cut_list = list1[1:4]
print(cut_list)
cut_list[0] = 100
print(cut_list)
print(list1)

[2, 3, 4]
[100, 3, 4]
[1, 2, 3, 4, 5, 6]


- <a href="https://proproprogs.ru/modules/numpy-indeksaciya-srezy-iterirovanie-massivov" target="_blank">ндексация, срезы</a>

In [10]:
#Создание копии массива
y = x.copy()
print(x)
print(y)
y[0] = 150
print('--------------')
print(x)
print(y)

[  1.1 101.    3.3   4.4   5.5]
[  1.1 101.    3.3   4.4   5.5]
--------------
[  1.1 101.    3.3   4.4   5.5]
[150.  101.    3.3   4.4   5.5]


In [14]:
#Задание для закрепления в презентации (сл. 27)
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube[1, 0, 1])
print('--------------')
print(cube[:, 1, 0])
print('--------------')
print(cube[:, 1])

6
--------------
[3 7]
--------------
[[3 4]
 [7 8]]


### <font color='teal'>3. Двумерные массивы и изменение размерности</font>

In [30]:
#зменение размерности
#Способ 1 (атрибут shape)
b = np.linspace(0, 3, 4)
print(b)
print(b.shape)
b.shape = 2, 2
print(b)

[0. 1. 2. 3.]
(4,)
[[0. 1.]
 [2. 3.]]


In [17]:
#Способ 2 (метод reshape)
print(np.linspace(0, 3, 4).reshape((2, 2)))

[[0. 1.]
 [2. 3.]]


In [32]:
#Превращение многомерного массива в одномерный 
#Способ 1 (функция ravel) - НЕ делает копию, т.е., изменения в a приведут к изменениям в исходном массиве
b = np.linspace(0, 3, 4).reshape(2, 2)
print(b)
a = b.ravel()
print(a)
a[0] = 123
print(a)
print(b)

[[0. 1.]
 [2. 3.]]
[0. 1. 2. 3.]
[123.   1.   2.   3.]
[[123.   1.]
 [  2.   3.]]


In [34]:
#Способ 2 (функция flatten) - делает копию, что не приводит к изменениям в исходном массиве
b = np.linspace(0, 3, 4).reshape(2, 2)
print(b)
a = b.flatten()
print(a)
a[0] = 123
print(a)
print(b)

[[0. 1.]
 [2. 3.]]
[0. 1. 2. 3.]
[123.   1.   2.   3.]
[[0. 1.]
 [2. 3.]]


- Двумерный массив называется <b> матрицей </b>
- <b> Квадратной матрицей </b> называется матрица, у которой количество строк и столбцов одинаково.
- <b> Транспонированная матрица </b> – матрица, в которой строки и столбцы поменяны местами.

<p align="center">
  <img src="../Images/trans.png" alt="Транспонированная матрица" width="800"/>
</p>

In [35]:
#Транспонирование матрицы
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### <font color='teal'>4. Умножение матриц</font>

#### <font color='teal'>4.1. Broadcasting</font>

<p align="center">
  <img src="../Images/Broadcasting_1.png" alt="Broadcasting" width="400"/>
</p>

<p align="center">
  <img src="../Images/Broadcasting_2.png" alt="Broadcasting" width="400"/>
</p>

<p align="center">
  <img src="../Images/Broadcasting_3.png" alt="Broadcasting" width="400"/>
</p>

In [2]:
#Поэлементное матричное умножение
a = np.array([1, 2, 3, 4])
b = np.array([[11, 12], [12, 11]])
print(a * b)

ValueError: operands could not be broadcast together with shapes (4,) (2,2) 

In [3]:
#Скалярное произведение векторов
a = np.array([1, 2, 3])
b = np.array([[11], [12], [13]])
print(a @ b)

[74]


<p align="center">
  <img src="../Images/vector_scalar.png" alt="Транспонированная матрица" width="800"/>
</p>

In [39]:
#Скалярное произведение матрицы на вектор
a = np.array([[1, 2, 3], [4, 0, 5]])
b = np.array([[11], [12], [13]])
print(a @ b)

[[ 74]
 [109]]


<p align="center">
  <img src="../Images/vector_matrix.png" alt="Транспонированная матрица" width="800"/>
</p>

In [40]:
#Скалярное произведение матрицы на матрицу
a = np.array([[1, 2, 3], [4, 0, 5]])
b = np.array([[11, 100], [12, 200], [13, 300]])
print(a @ b)

[[  74 1400]
 [ 109 1900]]


<p align="center">
  <img src="../Images/matrix_matrix.png" alt="Транспонированная матрица" width="800"/>
</p>

- <a href="https://mathprofi.ru/deistviya_s_matricami.html" target="_blank">Действия с матрицами</a>

In [ ]:
#Упражнение из презентации

### <font color='teal'>5. Решение задач</font>

##### 1) Что будет выведено в следующих случаях и почему?

In [5]:
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube[:, 0])
print("--------------")
print(cube[1, :, 0])
print("--------------")
s = cube[:, 1]
s *= 10
print(s)
print("--------------")
print(cube)

[[1 2]
 [5 6]]
--------------
[5 7]
--------------
[[30 40]
 [70 80]]
--------------
[[[ 1  2]
  [30 40]]

 [[ 5  6]
  [70 80]]]


##### 2) Умножьте матрицу a на b из отрывка кода ниже. Сначала самостоятельно, потом напишите код на Python. Проделайте аналогичные шаги для умножения матрицы b на матрицу a.

In [7]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a * b)
print("--------------")
print(a @ b)


[[ 5 12]
 [21 32]]
--------------
[[19 22]
 [43 50]]
