In [ ]:
import numpy as np
import pandas as pn

1. Сложение двух массивов:

   Напишите программу, которая:

   - Запрашивает у пользователя ввод двух одномерных массивов одинаковой длины. Массивы вводятся в виде чисел, разделенных пробелами.

   - Преобразует введенные строки в массивы NumPy.

   - Складывает два массива поэлементно.

   - Выводит результат сложения на экран.


   Пример вывода:


   Введите первый массив: 1 2 3

   Введите второй массив: 4 5 6


   Результат сложения: [5 7 9]

In [22]:
str_1 = input("Введите первый массив: ")
print(str_1)
str_2 = input("Введите второй массив: ")
print(str_2)
arr_1 = np.array(list(map(int, str_1.split())))
arr_2 = np.array(list(map(int, str_2.split()))) 
arr_sum = arr_1 + arr_2
print("-"*20)
print(arr_sum)


1 2 3
4 5 6
--------------------
[5 7 9]


2. Поэлементное умножение массивов:

   Напишите программу, которая:

   - Запрашивает у пользователя размер массивов N.

   - Генерирует два одномерных массива длины N с случайными целыми числами от 1 до 10.

   - Выводит оба сгенерированных массива на экран.

   - Выполняет поэлементное умножение массивов.

   - Выводит результат умножения на экран.


   Пример вывода:


   Введите размер массивов: 3


   Первый массив: [2, 6, 4]

   Второй массив: [1, 3, 5]


   Результат умножения: [2 18 20]

In [21]:
import random
size = int(input("Введите размер массива: "))
a = random.choices(range(1, 11), k=size)
b = random.choices(range(1, 11), k=size)
arr_1 = np.array(a)
arr_2 = np.array(b)
print(arr_1)
print("-"*20)
print(arr_2)
print("="*20)
print(arr_1 * arr_2)

[ 3 10  1]
--------------------
[2 1 1]
[ 6 10  1]


In [20]:
size = int(input("Введите размер массива: "))
arr_1 = np.random.randint(1, 11, size)
arr_2 = np.random.randint(1, 11, size)
print(arr_1)
print("-"*20)
print(arr_2)
print("="*20)
print(arr_1 * arr_2)

[8 5 5]
--------------------
[2 8 3]
[16 40 15]


3. Создание и модификация массива:

   Напишите программу, которая:

   - Запрашивает у пользователя количество элементов массива N.

   - Генерирует одномерный массив длины N, заполненный случайными числами от 0 до 100.

   - Выводит сгенерированный массив на экран.

   - Запрашивает у пользователя число X.

   - Умножает каждый элемент массива на число X.

   - Выводит измененный массив на экран.


   Пример вывода:

 

    Введите количество элементов массива: 4

    Сгенерированный массив: [20, 50, 30, 10]

    Введите число для умножения: 2


    Измененный массив: [40, 100, 60, 20]

In [ ]:
size = int(input("Введите размер массива: "))
arr = np.random.randint(0, 101, size)
print(arr)
x = int(input("Введите множитель: "))
print(arr * x)

[81  3  2 12]
[324  12   8  48]


In [ ]:
import seaborn as 