In [1]:
import numpy as np

1. Индексация массивов NumPy:


Напишите программу, которая:

- Запрашивает у пользователя ввод одномерного массива, элементы которого вводятся в виде чисел, разделенных пробелами.

- Преобразует введенную строку в массив NumPy.

- Запрашивает у пользователя индекс элемента, который необходимо извлечь из массива.

- Выводит значение элемента по запрошенному индексу.

- Запрашивает у пользователя ввод диапазона индексов в формате `начало:конец`, чтобы извлечь срез массива.

- Выводит срез массива.


Пример вывода:


Введите массив: 1 2 3 4 5

Введите индекс элемента: 2

Элемент с индексом 2: 3

Введите диапазон индексов (начало:конец): 1:4

Срез массива: [2 3 4]

In [2]:
str_input = input("Введите одномерный массив через пробел: ")
arr_1 = np.array(list(map(int, str_input.split())))
print("Исходный массив:", arr_1)
index = int(input(f"Введите индекс элемента для замены (от 0 до {len(arr_1)-1}): "))
print(f"Текущий элемент на позиции {index}:", arr_1[index])
diapozon = input("Введите диапазон в формате начало:конец ")
start, end = map(int, diapozon.split(':'))
print("Срез массива:", arr_1[start:end])

Исходный массив: [1 2 3 4 5]
Текущий элемент на позиции 3: 4
Срез массива: [2 3 4]


2. Операции с матрицами в NumPy:

Напишите программу, которая:

- Запрашивает у пользователя размеры матрицы MxN.

- Генерирует две матрицы указанных размеров, заполненные случайными числами от 0 до 9.

- Выводит обе сгенерированные матрицы на экран.

- Выполняет и выводит результат одной из следующих операций (на выбор пользователя): сложение матриц, умножение матриц, транспонирование одной из матриц.

- Если выбрано умножение, убедитесь, что размеры матриц соответствуют правилам матричного умножения.

Пример вывода:

Введите размеры матрицы MxN: 2x3

Первая матрица:

[[1 2 3]
 [4 5 6]]

Вторая матрица:

[[6 5 4]
 [3 2 1]]

Выберите операцию (сложение, умножение, транспонирование): сложение

Результат сложения:

[[ 7  7  7]

 [ 7  7  7]]

In [9]:
M, N = map(int, input("Введите размеры матрицы M*N через пробел: ").split())
arr_1 = np.random.randint(0, 10, size=(M, N))
print("Исходная матрица:\n", arr_1)
arr_2 = np.random.randint(0, 10, size=(M, N))
print("Вторая матрица:\n", arr_2)
choice = input(f"""Выберите операцию: \n
               1 - сложение\n
               2 - умножение\n
               3 - транспонирование\n""")
if choice == '1':
    print("Сложение матриц:\n", arr_1 + arr_2)
elif choice == '2':
    print("Умножение матриц:\n", arr_1 @ arr_2.T)
elif choice == '3':
    print("Транспонирование матриц:\n", arr_1.T)

Исходная матрица:
 [[3 4 5]
 [4 3 0]]
Вторая матрица:
 [[5 1 3]
 [4 1 1]]
Транспонирование матриц:
 [[3 4]
 [4 3]
 [5 0]]
